// proto/nydux/rec/v1/recommendation.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/rec/v1/recommendation.proto

package recv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecState int32

const (
	RecState_REC_STATE_UNSPECIFIED RecState = 0
	RecState_REC_STATE_CREATED     RecState = 1
	RecState_REC_STATE_APPROVED    RecState = 2
	RecState_REC_STATE_REJECTED    RecState = 3
	RecState_REC_STATE_APPLIED     RecState = 4
	RecState_REC_STATE_VERIFIED    RecState = 5
	RecState_REC_STATE_FAILED      RecState = 6
	RecState_REC_STATE_ROLLED_BACK RecState = 7
)

// Enum value maps for RecState.
var (
	RecState_name = map[int32]string{
		0: "REC_STATE_UNSPECIFIED",
		1: "REC_STATE_CREATED",
		2: "REC_STATE_APPROVED",
		3: "REC_STATE_REJECTED",
		4: "REC_STATE_APPLIED",
		5: "REC_STATE_VERIFIED",
		6: "REC_STATE_FAILED",
		7: "REC_STATE_ROLLED_BACK",
	}
	RecState_value = map[string]int32{
		"REC_STATE_UNSPECIFIED": 0,
		"REC_STATE_CREATED":     1,
		"REC_STATE_APPROVED":    2,
		"REC_STATE_REJECTED":    3,
		"REC_STATE_APPLIED":     4,
		"REC_STATE_VERIFIED":    5,
		"REC_STATE_FAILED":      6,
		"REC_STATE_ROLLED_BACK": 7,
	}
)

func (x RecState) Enum() *RecState {
	p := new(RecState)
	*p = x
	return p
}

func (x RecState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecState) Descriptor() protoreflect.EnumDescriptor {
	return file_nydux_rec_v1_recommendation_proto_enumTypes[0].Descriptor()
}

func (RecState) Type() protoreflect.EnumType {
	return &file_nydux_rec_v1_recommendation_proto_enumTypes[0]
}

func (x RecState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecState.Descriptor instead.
func (RecState) EnumDescriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

type EvidenceKind int32

const (
	EvidenceKind_EVIDENCE_KIND_UNSPECIFIED EvidenceKind = 0
	EvidenceKind_EVIDENCE_KIND_COUNTER     EvidenceKind = 1
	EvidenceKind_EVIDENCE_KIND_IR_SPAN     EvidenceKind = 2
	EvidenceKind_EVIDENCE_KIND_RUN         EvidenceKind = 3
	EvidenceKind_EVIDENCE_KIND_GRAPH       EvidenceKind = 4
)

// Enum value maps for EvidenceKind.
var (
	EvidenceKind_name = map[int32]string{
		0: "EVIDENCE_KIND_UNSPECIFIED",
		1: "EVIDENCE_KIND_COUNTER",
		2: "EVIDENCE_KIND_IR_SPAN",
		3: "EVIDENCE_KIND_RUN",
		4: "EVIDENCE_KIND_GRAPH",
	}
	EvidenceKind_value = map[string]int32{
		"EVIDENCE_KIND_UNSPECIFIED": 0,
		"EVIDENCE_KIND_COUNTER":     1,
		"EVIDENCE_KIND_IR_SPAN":     2,
		"EVIDENCE_KIND_RUN":         3,
		"EVIDENCE_KIND_GRAPH":       4,
	}
)

func (x EvidenceKind) Enum() *EvidenceKind {
	p := new(EvidenceKind)
	*p = x
	return p
}

func (x EvidenceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_nydux_rec_v1_recommendation_proto_enumTypes[1].Descriptor()
}

func (EvidenceKind) Type() protoreflect.EnumType {
	return &file_nydux_rec_v1_recommendation_proto_enumTypes[1]
}

func (x EvidenceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceKind.Descriptor instead.
func (EvidenceKind) EnumDescriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

type EvidenceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EvidenceKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=nydux.rec.v1.EvidenceKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Locator       string                 `protobuf:"bytes,3,opt,name=locator,proto3" json:"locator,omitempty"` // e.g. blob URI (in-tenant), graph query id, run id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceRef) Reset() {
	*x = EvidenceRef{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRef) ProtoMessage() {}

func (x *EvidenceRef) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRef.ProtoReflect.Descriptor instead.
func (*EvidenceRef) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceRef) GetKind() EvidenceKind {
	if x != nil {
		return x.Kind
	}
	return EvidenceKind_EVIDENCE_KIND_UNSPECIFIED
}

func (x *EvidenceRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvidenceRef) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*EvidenceRef         `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *Evidence) GetRefs() []*EvidenceRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type Recommendation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RecId      string                 `protobuf:"bytes,1,opt,name=rec_id,json=recId,proto3" json:"rec_id,omitempty"`
	KernelHash string                 `protobuf:"bytes,2,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	// Closed pattern set per ECD-003 §3.3.
	PatternId     string    `protobuf:"bytes,3,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id,omitempty"`
	GainP50       float64   `protobuf:"fixed64,4,opt,name=gain_p50,json=gainP50,proto3" json:"gain_p50,omitempty"`
	GainP90       float64   `protobuf:"fixed64,5,opt,name=gain_p90,json=gainP90,proto3" json:"gain_p90,omitempty"`
	Confidence    float64   `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Effort        string    `protobuf:"bytes,7,opt,name=effort,proto3" json:"effort,omitempty"`
	Risk          float64   `protobuf:"fixed64,8,opt,name=risk,proto3" json:"risk,omitempty"`
	State         RecState  `protobuf:"varint,9,opt,name=state,proto3,enum=nydux.rec.v1.RecState" json:"state,omitempty"`
	Evidence      *Evidence `protobuf:"bytes,10,opt,name=evidence,proto3" json:"evidence,omitempty"`
	PatchUri      string    `protobuf:"bytes,11,opt,name=patch_uri,json=patchUri,proto3" json:"patch_uri,omitempty"` // in-tenant blob; empty when human-instructions-only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *Recommendation) GetRecId() string {
	if x != nil {
		return x.RecId
	}
	return ""
}

func (x *Recommendation) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

func (x *Recommendation) GetPatternId() string {
	if x != nil {
		return x.PatternId
	}
	return ""
}

func (x *Recommendation) GetGainP50() float64 {
	if x != nil {
		return x.GainP50
	}
	return 0
}

func (x *Recommendation) GetGainP90() float64 {
	if x != nil {
		return x.GainP90
	}
	return 0
}

func (x *Recommendation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Recommendation) GetEffort() string {
	if x != nil {
		return x.Effort
	}
	return ""
}

func (x *Recommendation) GetRisk() float64 {
	if x != nil {
		return x.Risk
	}
	return 0
}

func (x *Recommendation) GetState() RecState {
	if x != nil {
		return x.State
	}
	return RecState_REC_STATE_UNSPECIFIED
}

func (x *Recommendation) GetEvidence() *Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Recommendation) GetPatchUri() string {
	if x != nil {
		return x.PatchUri
	}
	return ""
}

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecId         string                 `protobuf:"bytes,1,opt,name=rec_id,json=recId,proto3" json:"rec_id,omitempty"`
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	Rationale     string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"` // required either way (RFC-010 K.3 item 8)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *DecideRequest) GetRecId() string {
	if x != nil {
		return x.RecId
	}
	return ""
}

func (x *DecideRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *DecideRequest) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type DecideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rec           *Recommendation        `protobuf:"bytes,1,opt,name=rec,proto3" json:"rec,omitempty"`
	ApprovalToken string                 `protobuf:"bytes,2,opt,name=approval_token,json=approvalToken,proto3" json:"approval_token,omitempty"` // signed, 24h exp; empty on reject (RFC-008 H.10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *DecideResponse) GetRec() *Recommendation {
	if x != nil {
		return x.Rec
	}
	return nil
}

func (x *DecideResponse) GetApprovalToken() string {
	if x != nil {
		return x.ApprovalToken
	}
	return ""
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecId         string                 `protobuf:"bytes,1,opt,name=rec_id,json=recId,proto3" json:"rec_id,omitempty"`
	ApprovalToken string                 `protobuf:"bytes,2,opt,name=approval_token,json=approvalToken,proto3" json:"approval_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetRecId() string {
	if x != nil {
		return x.RecId
	}
	return ""
}

func (x *ApplyRequest) GetApprovalToken() string {
	if x != nil {
		return x.ApprovalToken
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeRef     string                 `protobuf:"bytes,1,opt,name=change_ref,json=changeRef,proto3" json:"change_ref,omitempty"`
	RollbackToken string                 `protobuf:"bytes,2,opt,name=rollback_token,json=rollbackToken,proto3" json:"rollback_token,omitempty"` // mandatory (RFC-008 H.6 rule 4)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_rec_v1_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_nydux_rec_v1_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyResponse) GetChangeRef() string {
	if x != nil {
		return x.ChangeRef
	}
	return ""
}

func (x *ApplyResponse) GetRollbackToken() string {
	if x != nil {
		return x.RollbackToken
	}
	return ""
}

var File_nydux_rec_v1_recommendation_proto protoreflect.FileDescriptor

const file_nydux_rec_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"!nydux/rec/v1/recommendation.proto\x12\fnydux.rec.v1\x1a\x1bbuf/validate/validate.proto\"g\n" +
	"\vEvidenceRef\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.nydux.rec.v1.EvidenceKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\alocator\x18\x03 \x01(\tR\alocator\"C\n" +
	"\bEvidence\x127\n" +
	"\x04refs\x18\x01 \x03(\v2\x19.nydux.rec.v1.EvidenceRefB\b\xbaH\x05\x92\x01\x02\b\x01R\x04refs\"\x9b\x05\n" +
	"\x0eRecommendation\x12\x1f\n" +
	"\x06rec_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05recId\x12)\n" +
	"\vkernel_hash\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\n" +
	"kernelHash\x12\xef\x01\n" +
	"\n" +
	"pattern_id\x18\x03 \x01(\tB\xcf\x01\xbaH\xcb\x01r\xc8\x01R\x13unfused_elementwiseR\x11missing_flashattnR\freg_pressureR\fnoncoalescedR\ffp32_gemm_tcR\x0fsmallbatch_gemmR\flaunch_stormR\vtriton_tileR\x0fcublas_fallbackR\x10comm_overlap_gapR\x11toolchain_upgradeR\x12toolchain_holdbackR\tpatternId\x12\x19\n" +
	"\bgain_p50\x18\x04 \x01(\x01R\againP50\x12\x19\n" +
	"\bgain_p90\x18\x05 \x01(\x01R\againP90\x127\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"confidence\x129\n" +
	"\x06effort\x18\a \x01(\tB!\xbaH\x1er\x1cR\atrivialR\x03lowR\x06mediumR\x04highR\x06effort\x12\"\n" +
	"\x04risk\x18\b \x01(\x01B\x0e\xbaH\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x04risk\x12,\n" +
	"\x05state\x18\t \x01(\x0e2\x16.nydux.rec.v1.RecStateR\x05state\x122\n" +
	"\bevidence\x18\n" +
	" \x01(\v2\x16.nydux.rec.v1.EvidenceR\bevidence\x12\x1b\n" +
	"\tpatch_uri\x18\v \x01(\tR\bpatchUri\"q\n" +
	"\rDecideRequest\x12\x1f\n" +
	"\x06rec_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05recId\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\x12%\n" +
	"\trationale\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x04R\trationale\"g\n" +
	"\x0eDecideResponse\x12.\n" +
	"\x03rec\x18\x01 \x01(\v2\x1c.nydux.rec.v1.RecommendationR\x03rec\x12%\n" +
	"\x0eapproval_token\x18\x02 \x01(\tR\rapprovalToken\"U\n" +
	"\fApplyRequest\x12\x15\n" +
	"\x06rec_id\x18\x01 \x01(\tR\x05recId\x12.\n" +
	"\x0eapproval_token\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x10R\rapprovalToken\"U\n" +
	"\rApplyResponse\x12\x1d\n" +
	"\n" +
	"change_ref\x18\x01 \x01(\tR\tchangeRef\x12%\n" +
	"\x0erollback_token\x18\x02 \x01(\tR\rrollbackToken*\xcc\x01\n" +
	"\bRecState\x12\x19\n" +
	"\x15REC_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11REC_STATE_CREATED\x10\x01\x12\x16\n" +
	"\x12REC_STATE_APPROVED\x10\x02\x12\x16\n" +
	"\x12REC_STATE_REJECTED\x10\x03\x12\x15\n" +
	"\x11REC_STATE_APPLIED\x10\x04\x12\x16\n" +
	"\x12REC_STATE_VERIFIED\x10\x05\x12\x14\n" +
	"\x10REC_STATE_FAILED\x10\x06\x12\x19\n" +
	"\x15REC_STATE_ROLLED_BACK\x10\a*\x93\x01\n" +
	"\fEvidenceKind\x12\x1d\n" +
	"\x19EVIDENCE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVIDENCE_KIND_COUNTER\x10\x01\x12\x19\n" +
	"\x15EVIDENCE_KIND_IR_SPAN\x10\x02\x12\x15\n" +
	"\x11EVIDENCE_KIND_RUN\x10\x03\x12\x17\n" +
	"\x13EVIDENCE_KIND_GRAPH\x10\x042\x9e\x01\n" +
	"\x15RecommendationService\x12C\n" +
	"\x06Decide\x12\x1b.nydux.rec.v1.DecideRequest\x1a\x1c.nydux.rec.v1.DecideResponse\x12@\n" +
	"\x05Apply\x12\x1a.nydux.rec.v1.ApplyRequest\x1a\x1b.nydux.rec.v1.ApplyResponseB2Z0github.com/nydux/platform/api/nydux/rec/v1;recv1b\x06proto3"

var (
	file_nydux_rec_v1_recommendation_proto_rawDescOnce sync.Once
	file_nydux_rec_v1_recommendation_proto_rawDescData []byte
)

func file_nydux_rec_v1_recommendation_proto_rawDescGZIP() []byte {
	file_nydux_rec_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_nydux_rec_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_rec_v1_recommendation_proto_rawDesc), len(file_nydux_rec_v1_recommendation_proto_rawDesc)))
	})
	return file_nydux_rec_v1_recommendation_proto_rawDescData
}

var file_nydux_rec_v1_recommendation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nydux_rec_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nydux_rec_v1_recommendation_proto_goTypes = []any{
	(RecState)(0),          // 0: nydux.rec.v1.RecState
	(EvidenceKind)(0),      // 1: nydux.rec.v1.EvidenceKind
	(*EvidenceRef)(nil),    // 2: nydux.rec.v1.EvidenceRef
	(*Evidence)(nil),       // 3: nydux.rec.v1.Evidence
	(*Recommendation)(nil), // 4: nydux.rec.v1.Recommendation
	(*DecideRequest)(nil),  // 5: nydux.rec.v1.DecideRequest
	(*DecideResponse)(nil), // 6: nydux.rec.v1.DecideResponse
	(*ApplyRequest)(nil),   // 7: nydux.rec.v1.ApplyRequest
	(*ApplyResponse)(nil),  // 8: nydux.rec.v1.ApplyResponse
}
var file_nydux_rec_v1_recommendation_proto_depIdxs = []int32{
	1, // 0: nydux.rec.v1.EvidenceRef.kind:type_name -> nydux.rec.v1.EvidenceKind
	2, // 1: nydux.rec.v1.Evidence.refs:type_name -> nydux.rec.v1.EvidenceRef
	0, // 2: nydux.rec.v1.Recommendation.state:type_name -> nydux.rec.v1.RecState
	3, // 3: nydux.rec.v1.Recommendation.evidence:type_name -> nydux.rec.v1.Evidence
	4, // 4: nydux.rec.v1.DecideResponse.rec:type_name -> nydux.rec.v1.Recommendation
	5, // 5: nydux.rec.v1.RecommendationService.Decide:input_type -> nydux.rec.v1.DecideRequest
	7, // 6: nydux.rec.v1.RecommendationService.Apply:input_type -> nydux.rec.v1.ApplyRequest
	6, // 7: nydux.rec.v1.RecommendationService.Decide:output_type -> nydux.rec.v1.DecideResponse
	8, // 8: nydux.rec.v1.RecommendationService.Apply:output_type -> nydux.rec.v1.ApplyResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_nydux_rec_v1_recommendation_proto_init() }
func file_nydux_rec_v1_recommendation_proto_init() {
	if File_nydux_rec_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_rec_v1_recommendation_proto_rawDesc), len(file_nydux_rec_v1_recommendation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_rec_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_nydux_rec_v1_recommendation_proto_depIdxs,
		EnumInfos:         file_nydux_rec_v1_recommendation_proto_enumTypes,
		MessageInfos:      file_nydux_rec_v1_recommendation_proto_msgTypes,
	}.Build()
	File_nydux_rec_v1_recommendation_proto = out.File
	file_nydux_rec_v1_recommendation_proto_goTypes = nil
	file_nydux_rec_v1_recommendation_proto_depIdxs = nil
}
