// proto/nydux/common/v1/envelope.proto
// Wire-truth event envelope. FROZEN per RFC-005 B.2 — additive changes only.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/common/v1/envelope.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7 — idempotency key for all consumers.
	EventId  string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Empty string for control-plane-origin events.
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Catalog type, e.g. "compiler.kernel.scored". Must match a row in event-registry.yaml.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Payload schema major version.
	SchemaVersion uint32 `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Occurrence time, device clock (NTP-disciplined), epoch nanoseconds.
	EventTimeNs  int64 `protobuf:"varint,6,opt,name=event_time_ns,json=eventTimeNs,proto3" json:"event_time_ns,omitempty"`
	IngestTimeNs int64 `protobuf:"varint,7,opt,name=ingest_time_ns,json=ingestTimeNs,proto3" json:"ingest_time_ns,omitempty"`
	// W3C traceparent value.
	TraceId string `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// "service@semver", e.g. "kernel-registry@1.4.2".
	Producer string `protobuf:"bytes,9,opt,name=producer,proto3" json:"producer,omitempty"`
	// Serialized payload message; concrete type given by `type` + schema registry.
	Payload []byte `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	// Kafka partition key as documented per event in event-registry.yaml.
	PartitionKey  string `protobuf:"bytes,11,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_nydux_common_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_common_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_nydux_common_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventEnvelope) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventEnvelope) GetEventTimeNs() int64 {
	if x != nil {
		return x.EventTimeNs
	}
	return 0
}

func (x *EventEnvelope) GetIngestTimeNs() int64 {
	if x != nil {
		return x.IngestTimeNs
	}
	return 0
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventEnvelope) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

// Shared error detail attached to gRPC status (RFC-006 F.5).
type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`                                                                               // catalog code, e.g. "gate_failed"
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                                                                               // always "nydux.ai"
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // must include "trace_id"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_nydux_common_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_common_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_nydux_common_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ErrorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_nydux_common_v1_envelope_proto protoreflect.FileDescriptor

const file_nydux_common_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1enydux/common/v1/envelope.proto\x12\x0fnydux.common.v1\x1a\x1bbuf/validate/validate.proto\"\xaa\x03\n" +
	"\rEventEnvelope\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12%\n" +
	"\ttenant_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1e\n" +
	"\x04type\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x03\x18\x80\x01R\x04type\x12.\n" +
	"\x0eschema_version\x18\x05 \x01(\rB\a\xbaH\x04*\x02(\x01R\rschemaVersion\x12+\n" +
	"\revent_time_ns\x18\x06 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\veventTimeNs\x12$\n" +
	"\x0eingest_time_ns\x18\a \x01(\x03R\fingestTimeNs\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12%\n" +
	"\bproducer\x18\t \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\bproducer\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x12/\n" +
	"\rpartition_key\x18\v \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\fpartitionKey\"\xbe\x01\n" +
	"\tErrorInfo\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.nydux.common.v1.ErrorInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B8Z6github.com/nydux/platform/api/nydux/common/v1;commonv1b\x06proto3"

var (
	file_nydux_common_v1_envelope_proto_rawDescOnce sync.Once
	file_nydux_common_v1_envelope_proto_rawDescData []byte
)

func file_nydux_common_v1_envelope_proto_rawDescGZIP() []byte {
	file_nydux_common_v1_envelope_proto_rawDescOnce.Do(func() {
		file_nydux_common_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_common_v1_envelope_proto_rawDesc), len(file_nydux_common_v1_envelope_proto_rawDesc)))
	})
	return file_nydux_common_v1_envelope_proto_rawDescData
}

var file_nydux_common_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nydux_common_v1_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil), // 0: nydux.common.v1.EventEnvelope
	(*ErrorInfo)(nil),     // 1: nydux.common.v1.ErrorInfo
	nil,                   // 2: nydux.common.v1.ErrorInfo.MetadataEntry
}
var file_nydux_common_v1_envelope_proto_depIdxs = []int32{
	2, // 0: nydux.common.v1.ErrorInfo.metadata:type_name -> nydux.common.v1.ErrorInfo.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nydux_common_v1_envelope_proto_init() }
func file_nydux_common_v1_envelope_proto_init() {
	if File_nydux_common_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_common_v1_envelope_proto_rawDesc), len(file_nydux_common_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nydux_common_v1_envelope_proto_goTypes,
		DependencyIndexes: file_nydux_common_v1_envelope_proto_depIdxs,
		MessageInfos:      file_nydux_common_v1_envelope_proto_msgTypes,
	}.Build()
	File_nydux_common_v1_envelope_proto = out.File
	file_nydux_common_v1_envelope_proto_goTypes = nil
	file_nydux_common_v1_envelope_proto_depIdxs = nil
}
