// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/infra/v1/gpu.proto

package infrav1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpuSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuUuid       string                 `protobuf:"bytes,1,opt,name=gpu_uuid,json=gpuUuid,proto3" json:"gpu_uuid,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Pod           string                 `protobuf:"bytes,3,opt,name=pod,proto3" json:"pod,omitempty"`
	Ns            string                 `protobuf:"bytes,4,opt,name=ns,proto3" json:"ns,omitempty"`
	SmUtil        float32                `protobuf:"fixed32,5,opt,name=sm_util,json=smUtil,proto3" json:"sm_util,omitempty"`
	MemUtil       float32                `protobuf:"fixed32,6,opt,name=mem_util,json=memUtil,proto3" json:"mem_util,omitempty"`
	MemUsedMb     uint32                 `protobuf:"varint,7,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	PowerW        float32                `protobuf:"fixed32,8,opt,name=power_w,json=powerW,proto3" json:"power_w,omitempty"`
	TempC         float32                `protobuf:"fixed32,9,opt,name=temp_c,json=tempC,proto3" json:"temp_c,omitempty"`
	SmClock       uint32                 `protobuf:"varint,10,opt,name=sm_clock,json=smClock,proto3" json:"sm_clock,omitempty"`
	PcieTxMb      float32                `protobuf:"fixed32,11,opt,name=pcie_tx_mb,json=pcieTxMb,proto3" json:"pcie_tx_mb,omitempty"`
	NvlinkTxMb    float32                `protobuf:"fixed32,12,opt,name=nvlink_tx_mb,json=nvlinkTxMb,proto3" json:"nvlink_tx_mb,omitempty"`
	TensorActive  float32                `protobuf:"fixed32,13,opt,name=tensor_active,json=tensorActive,proto3" json:"tensor_active,omitempty"`
	DramActive    float32                `protobuf:"fixed32,14,opt,name=dram_active,json=dramActive,proto3" json:"dram_active,omitempty"`
	Xid           uint32                 `protobuf:"varint,15,opt,name=xid,proto3" json:"xid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuSample) Reset() {
	*x = GpuSample{}
	mi := &file_nydux_infra_v1_gpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuSample) ProtoMessage() {}

func (x *GpuSample) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_infra_v1_gpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuSample.ProtoReflect.Descriptor instead.
func (*GpuSample) Descriptor() ([]byte, []int) {
	return file_nydux_infra_v1_gpu_proto_rawDescGZIP(), []int{0}
}

func (x *GpuSample) GetGpuUuid() string {
	if x != nil {
		return x.GpuUuid
	}
	return ""
}

func (x *GpuSample) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GpuSample) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *GpuSample) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *GpuSample) GetSmUtil() float32 {
	if x != nil {
		return x.SmUtil
	}
	return 0
}

func (x *GpuSample) GetMemUtil() float32 {
	if x != nil {
		return x.MemUtil
	}
	return 0
}

func (x *GpuSample) GetMemUsedMb() uint32 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *GpuSample) GetPowerW() float32 {
	if x != nil {
		return x.PowerW
	}
	return 0
}

func (x *GpuSample) GetTempC() float32 {
	if x != nil {
		return x.TempC
	}
	return 0
}

func (x *GpuSample) GetSmClock() uint32 {
	if x != nil {
		return x.SmClock
	}
	return 0
}

func (x *GpuSample) GetPcieTxMb() float32 {
	if x != nil {
		return x.PcieTxMb
	}
	return 0
}

func (x *GpuSample) GetNvlinkTxMb() float32 {
	if x != nil {
		return x.NvlinkTxMb
	}
	return 0
}

func (x *GpuSample) GetTensorActive() float32 {
	if x != nil {
		return x.TensorActive
	}
	return 0
}

func (x *GpuSample) GetDramActive() float32 {
	if x != nil {
		return x.DramActive
	}
	return 0
}

func (x *GpuSample) GetXid() uint32 {
	if x != nil {
		return x.Xid
	}
	return 0
}

type NodeHealth struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Node               string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	State              string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	RecentXids         []uint32               `protobuf:"varint,3,rep,packed,name=recent_xids,json=recentXids,proto3" json:"recent_xids,omitempty"`
	EccDbeRate         float32                `protobuf:"fixed32,4,opt,name=ecc_dbe_rate,json=eccDbeRate,proto3" json:"ecc_dbe_rate,omitempty"`
	NvlinkReplayRate   float32                `protobuf:"fixed32,5,opt,name=nvlink_replay_rate,json=nvlinkReplayRate,proto3" json:"nvlink_replay_rate,omitempty"`
	ThermalThrottlePct float32                `protobuf:"fixed32,6,opt,name=thermal_throttle_pct,json=thermalThrottlePct,proto3" json:"thermal_throttle_pct,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeHealth) Reset() {
	*x = NodeHealth{}
	mi := &file_nydux_infra_v1_gpu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealth) ProtoMessage() {}

func (x *NodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_infra_v1_gpu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealth.ProtoReflect.Descriptor instead.
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return file_nydux_infra_v1_gpu_proto_rawDescGZIP(), []int{1}
}

func (x *NodeHealth) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeHealth) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeHealth) GetRecentXids() []uint32 {
	if x != nil {
		return x.RecentXids
	}
	return nil
}

func (x *NodeHealth) GetEccDbeRate() float32 {
	if x != nil {
		return x.EccDbeRate
	}
	return 0
}

func (x *NodeHealth) GetNvlinkReplayRate() float32 {
	if x != nil {
		return x.NvlinkReplayRate
	}
	return 0
}

func (x *NodeHealth) GetThermalThrottlePct() float32 {
	if x != nil {
		return x.ThermalThrottlePct
	}
	return 0
}

type DeviceInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuUuid       string                 `protobuf:"bytes,1,opt,name=gpu_uuid,json=gpuUuid,proto3" json:"gpu_uuid,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`                                 // e.g. "H100-SXM5-80GB"
	MigProfile    string                 `protobuf:"bytes,4,opt,name=mig_profile,json=migProfile,proto3" json:"mig_profile,omitempty"` // empty = whole GPU
	Driver        string                 `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"`
	Vbios         string                 `protobuf:"bytes,6,opt,name=vbios,proto3" json:"vbios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInventory) Reset() {
	*x = DeviceInventory{}
	mi := &file_nydux_infra_v1_gpu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInventory) ProtoMessage() {}

func (x *DeviceInventory) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_infra_v1_gpu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInventory.ProtoReflect.Descriptor instead.
func (*DeviceInventory) Descriptor() ([]byte, []int) {
	return file_nydux_infra_v1_gpu_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInventory) GetGpuUuid() string {
	if x != nil {
		return x.GpuUuid
	}
	return ""
}

func (x *DeviceInventory) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *DeviceInventory) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DeviceInventory) GetMigProfile() string {
	if x != nil {
		return x.MigProfile
	}
	return ""
}

func (x *DeviceInventory) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DeviceInventory) GetVbios() string {
	if x != nil {
		return x.Vbios
	}
	return ""
}

var File_nydux_infra_v1_gpu_proto protoreflect.FileDescriptor

const file_nydux_infra_v1_gpu_proto_rawDesc = "" +
	"\n" +
	"\x18nydux/infra/v1/gpu.proto\x12\x0enydux.infra.v1\x1a\x1bbuf/validate/validate.proto\"\xe0\x03\n" +
	"\tGpuSample\x12\"\n" +
	"\bgpu_uuid\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agpuUuid\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x10\n" +
	"\x03pod\x18\x03 \x01(\tR\x03pod\x12\x0e\n" +
	"\x02ns\x18\x04 \x01(\tR\x02ns\x12(\n" +
	"\asm_util\x18\x05 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\xc8B-\x00\x00\x00\x00R\x06smUtil\x12*\n" +
	"\bmem_util\x18\x06 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\xc8B-\x00\x00\x00\x00R\amemUtil\x12\x1e\n" +
	"\vmem_used_mb\x18\a \x01(\rR\tmemUsedMb\x12\x17\n" +
	"\apower_w\x18\b \x01(\x02R\x06powerW\x12\x15\n" +
	"\x06temp_c\x18\t \x01(\x02R\x05tempC\x12\x19\n" +
	"\bsm_clock\x18\n" +
	" \x01(\rR\asmClock\x12\x1c\n" +
	"\n" +
	"pcie_tx_mb\x18\v \x01(\x02R\bpcieTxMb\x12 \n" +
	"\fnvlink_tx_mb\x18\f \x01(\x02R\n" +
	"nvlinkTxMb\x124\n" +
	"\rtensor_active\x18\r \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\ftensorActive\x120\n" +
	"\vdram_active\x18\x0e \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\n" +
	"dramActive\x12\x10\n" +
	"\x03xid\x18\x0f \x01(\rR\x03xid\"\x89\x02\n" +
	"\n" +
	"NodeHealth\x12\x1b\n" +
	"\x04node\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04node\x12;\n" +
	"\x05state\x18\x02 \x01(\tB%\xbaH\"r R\x02okR\awarningR\afailingR\bcordonedR\x05state\x12\x1f\n" +
	"\vrecent_xids\x18\x03 \x03(\rR\n" +
	"recentXids\x12 \n" +
	"\fecc_dbe_rate\x18\x04 \x01(\x02R\n" +
	"eccDbeRate\x12,\n" +
	"\x12nvlink_replay_rate\x18\x05 \x01(\x02R\x10nvlinkReplayRate\x120\n" +
	"\x14thermal_throttle_pct\x18\x06 \x01(\x02R\x12thermalThrottlePct\"\xa1\x01\n" +
	"\x0fDeviceInventory\x12\x19\n" +
	"\bgpu_uuid\x18\x01 \x01(\tR\agpuUuid\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x1f\n" +
	"\vmig_profile\x18\x04 \x01(\tR\n" +
	"migProfile\x12\x16\n" +
	"\x06driver\x18\x05 \x01(\tR\x06driver\x12\x14\n" +
	"\x05vbios\x18\x06 \x01(\tR\x05vbiosB6Z4github.com/nydux/platform/api/nydux/infra/v1;infrav1b\x06proto3"

var (
	file_nydux_infra_v1_gpu_proto_rawDescOnce sync.Once
	file_nydux_infra_v1_gpu_proto_rawDescData []byte
)

func file_nydux_infra_v1_gpu_proto_rawDescGZIP() []byte {
	file_nydux_infra_v1_gpu_proto_rawDescOnce.Do(func() {
		file_nydux_infra_v1_gpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_infra_v1_gpu_proto_rawDesc), len(file_nydux_infra_v1_gpu_proto_rawDesc)))
	})
	return file_nydux_infra_v1_gpu_proto_rawDescData
}

var file_nydux_infra_v1_gpu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nydux_infra_v1_gpu_proto_goTypes = []any{
	(*GpuSample)(nil),       // 0: nydux.infra.v1.GpuSample
	(*NodeHealth)(nil),      // 1: nydux.infra.v1.NodeHealth
	(*DeviceInventory)(nil), // 2: nydux.infra.v1.DeviceInventory
}
var file_nydux_infra_v1_gpu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nydux_infra_v1_gpu_proto_init() }
func file_nydux_infra_v1_gpu_proto_init() {
	if File_nydux_infra_v1_gpu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_infra_v1_gpu_proto_rawDesc), len(file_nydux_infra_v1_gpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nydux_infra_v1_gpu_proto_goTypes,
		DependencyIndexes: file_nydux_infra_v1_gpu_proto_depIdxs,
		MessageInfos:      file_nydux_infra_v1_gpu_proto_msgTypes,
	}.Build()
	File_nydux_infra_v1_gpu_proto = out.File
	file_nydux_infra_v1_gpu_proto_goTypes = nil
	file_nydux_infra_v1_gpu_proto_depIdxs = nil
}
