{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: {name: {{ .Values.name }}, labels: {release: prometheus, {{- include "nydux.labels" . | nindent 4 }}}}
spec:
  selector: {matchLabels: {app.kubernetes.io/name: {{ .Values.name }}}}
  endpoints: [{port: ops, path: /metrics, interval: {{ .Values.serviceMonitor.interval }}}]
{{- end }}
