// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/audit/v1/audit.proto

package auditv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	EntryHash     []byte                 `protobuf:"bytes,2,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`                                // "user:<uuid>"|"svc:<name>"|"agent:<task>"
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                              // closed catalog in ECD-012
	SubjectJson   []byte                 `protobuf:"bytes,6,opt,name=subject_json,json=subjectJson,proto3" json:"subject_json,omitempty"` // canonical JSON
	AtNs          int64                  `protobuf:"varint,7,opt,name=at_ns,json=atNs,proto3" json:"at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_nydux_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AuditEntry) GetEntryHash() []byte {
	if x != nil {
		return x.EntryHash
	}
	return nil
}

func (x *AuditEntry) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetSubjectJson() []byte {
	if x != nil {
		return x.SubjectJson
	}
	return nil
}

func (x *AuditEntry) GetAtNs() int64 {
	if x != nil {
		return x.AtNs
	}
	return 0
}

type AuditAppended struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AuditEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppended) Reset() {
	*x = AuditAppended{}
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppended) ProtoMessage() {}

func (x *AuditAppended) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppended.ProtoReflect.Descriptor instead.
func (*AuditAppended) Descriptor() ([]byte, []int) {
	return file_nydux_audit_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditAppended) GetEntry() *AuditEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AuditEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_nydux_audit_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRequest) GetEntry() *AuditEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	EntryHash     []byte                 `protobuf:"bytes,2,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_nydux_audit_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AppendResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AppendResponse) GetEntryHash() []byte {
	if x != nil {
		return x.EntryHash
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSeq       int64                  `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_nydux_audit_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type VerifyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Valid              bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	VerifiedThroughSeq int64                  `protobuf:"varint,2,opt,name=verified_through_seq,json=verifiedThroughSeq,proto3" json:"verified_through_seq,omitempty"`
	FirstBadSeq        int64                  `protobuf:"varint,3,opt,name=first_bad_seq,json=firstBadSeq,proto3" json:"first_bad_seq,omitempty"` // 0 when valid
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_audit_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_nydux_audit_v1_audit_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetVerifiedThroughSeq() int64 {
	if x != nil {
		return x.VerifiedThroughSeq
	}
	return 0
}

func (x *VerifyResponse) GetFirstBadSeq() int64 {
	if x != nil {
		return x.FirstBadSeq
	}
	return 0
}

var File_nydux_audit_v1_audit_proto protoreflect.FileDescriptor

const file_nydux_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x1anydux/audit/v1/audit.proto\x12\x0enydux.audit.v1\x1a\x1bbuf/validate/validate.proto\"\xed\x01\n" +
	"\n" +
	"AuditEntry\x12\x19\n" +
	"\x03seq\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x03seq\x12&\n" +
	"\n" +
	"entry_hash\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\tentryHash\x12$\n" +
	"\tprev_hash\x18\x03 \x01(\fB\a\xbaH\x04z\x02h R\bprevHash\x12\x1d\n" +
	"\x05actor\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05actor\x12\x1f\n" +
	"\x06action\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06action\x12!\n" +
	"\fsubject_json\x18\x06 \x01(\fR\vsubjectJson\x12\x13\n" +
	"\x05at_ns\x18\a \x01(\x03R\x04atNs\"A\n" +
	"\rAuditAppended\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.nydux.audit.v1.AuditEntryR\x05entry\"A\n" +
	"\rAppendRequest\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.nydux.audit.v1.AuditEntryR\x05entry\"A\n" +
	"\x0eAppendResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1d\n" +
	"\n" +
	"entry_hash\x18\x02 \x01(\fR\tentryHash\"*\n" +
	"\rVerifyRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x03R\afromSeq\"|\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x120\n" +
	"\x14verified_through_seq\x18\x02 \x01(\x03R\x12verifiedThroughSeq\x12\"\n" +
	"\rfirst_bad_seq\x18\x03 \x01(\x03R\vfirstBadSeq2\xa0\x01\n" +
	"\fAuditService\x12G\n" +
	"\x06Append\x12\x1d.nydux.audit.v1.AppendRequest\x1a\x1e.nydux.audit.v1.AppendResponse\x12G\n" +
	"\x06Verify\x12\x1d.nydux.audit.v1.VerifyRequest\x1a\x1e.nydux.audit.v1.VerifyResponseB6Z4github.com/nydux/platform/api/nydux/audit/v1;auditv1b\x06proto3"

var (
	file_nydux_audit_v1_audit_proto_rawDescOnce sync.Once
	file_nydux_audit_v1_audit_proto_rawDescData []byte
)

func file_nydux_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_nydux_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_nydux_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_audit_v1_audit_proto_rawDesc), len(file_nydux_audit_v1_audit_proto_rawDesc)))
	})
	return file_nydux_audit_v1_audit_proto_rawDescData
}

var file_nydux_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nydux_audit_v1_audit_proto_goTypes = []any{
	(*AuditEntry)(nil),     // 0: nydux.audit.v1.AuditEntry
	(*AuditAppended)(nil),  // 1: nydux.audit.v1.AuditAppended
	(*AppendRequest)(nil),  // 2: nydux.audit.v1.AppendRequest
	(*AppendResponse)(nil), // 3: nydux.audit.v1.AppendResponse
	(*VerifyRequest)(nil),  // 4: nydux.audit.v1.VerifyRequest
	(*VerifyResponse)(nil), // 5: nydux.audit.v1.VerifyResponse
}
var file_nydux_audit_v1_audit_proto_depIdxs = []int32{
	0, // 0: nydux.audit.v1.AuditAppended.entry:type_name -> nydux.audit.v1.AuditEntry
	0, // 1: nydux.audit.v1.AppendRequest.entry:type_name -> nydux.audit.v1.AuditEntry
	2, // 2: nydux.audit.v1.AuditService.Append:input_type -> nydux.audit.v1.AppendRequest
	4, // 3: nydux.audit.v1.AuditService.Verify:input_type -> nydux.audit.v1.VerifyRequest
	3, // 4: nydux.audit.v1.AuditService.Append:output_type -> nydux.audit.v1.AppendResponse
	5, // 5: nydux.audit.v1.AuditService.Verify:output_type -> nydux.audit.v1.VerifyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nydux_audit_v1_audit_proto_init() }
func file_nydux_audit_v1_audit_proto_init() {
	if File_nydux_audit_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_audit_v1_audit_proto_rawDesc), len(file_nydux_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_nydux_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_nydux_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_nydux_audit_v1_audit_proto = out.File
	file_nydux_audit_v1_audit_proto_goTypes = nil
	file_nydux_audit_v1_audit_proto_depIdxs = nil
}
