// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/runtime/v1/serving.proto

package runtimev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deploy        string                 `protobuf:"bytes,1,opt,name=deploy,proto3" json:"deploy,omitempty"`
	TtftMs        float32                `protobuf:"fixed32,2,opt,name=ttft_ms,json=ttftMs,proto3" json:"ttft_ms,omitempty"`
	TpotMs        float32                `protobuf:"fixed32,3,opt,name=tpot_ms,json=tpotMs,proto3" json:"tpot_ms,omitempty"`
	Batch         uint32                 `protobuf:"varint,4,opt,name=batch,proto3" json:"batch,omitempty"`
	KvHit         float32                `protobuf:"fixed32,5,opt,name=kv_hit,json=kvHit,proto3" json:"kv_hit,omitempty"`
	Req           uint32                 `protobuf:"varint,6,opt,name=req,proto3" json:"req,omitempty"`
	TokensIn      uint64                 `protobuf:"varint,7,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut     uint64                 `protobuf:"varint,8,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServingMetrics) Reset() {
	*x = ServingMetrics{}
	mi := &file_nydux_runtime_v1_serving_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServingMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServingMetrics) ProtoMessage() {}

func (x *ServingMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_runtime_v1_serving_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServingMetrics.ProtoReflect.Descriptor instead.
func (*ServingMetrics) Descriptor() ([]byte, []int) {
	return file_nydux_runtime_v1_serving_proto_rawDescGZIP(), []int{0}
}

func (x *ServingMetrics) GetDeploy() string {
	if x != nil {
		return x.Deploy
	}
	return ""
}

func (x *ServingMetrics) GetTtftMs() float32 {
	if x != nil {
		return x.TtftMs
	}
	return 0
}

func (x *ServingMetrics) GetTpotMs() float32 {
	if x != nil {
		return x.TpotMs
	}
	return 0
}

func (x *ServingMetrics) GetBatch() uint32 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *ServingMetrics) GetKvHit() float32 {
	if x != nil {
		return x.KvHit
	}
	return 0
}

func (x *ServingMetrics) GetReq() uint32 {
	if x != nil {
		return x.Req
	}
	return 0
}

func (x *ServingMetrics) GetTokensIn() uint64 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *ServingMetrics) GetTokensOut() uint64 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

type NcclCollective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           string                 `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Bytes         uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	DurationUs    float32                `protobuf:"fixed32,4,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	BusbwGbps     float32                `protobuf:"fixed32,5,opt,name=busbw_gbps,json=busbwGbps,proto3" json:"busbw_gbps,omitempty"`
	Ranks         uint32                 `protobuf:"varint,6,opt,name=ranks,proto3" json:"ranks,omitempty"`
	Algo          string                 `protobuf:"bytes,7,opt,name=algo,proto3" json:"algo,omitempty"`   // ring|tree|collnet
	Proto         string                 `protobuf:"bytes,8,opt,name=proto,proto3" json:"proto,omitempty"` // LL|LL128|Simple
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NcclCollective) Reset() {
	*x = NcclCollective{}
	mi := &file_nydux_runtime_v1_serving_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NcclCollective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NcclCollective) ProtoMessage() {}

func (x *NcclCollective) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_runtime_v1_serving_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NcclCollective.ProtoReflect.Descriptor instead.
func (*NcclCollective) Descriptor() ([]byte, []int) {
	return file_nydux_runtime_v1_serving_proto_rawDescGZIP(), []int{1}
}

func (x *NcclCollective) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *NcclCollective) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NcclCollective) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *NcclCollective) GetDurationUs() float32 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *NcclCollective) GetBusbwGbps() float32 {
	if x != nil {
		return x.BusbwGbps
	}
	return 0
}

func (x *NcclCollective) GetRanks() uint32 {
	if x != nil {
		return x.Ranks
	}
	return 0
}

func (x *NcclCollective) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *NcclCollective) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

type TrainingStep struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Job              string                 `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Step             uint64                 `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	StepTimeMs       float32                `protobuf:"fixed32,3,opt,name=step_time_ms,json=stepTimeMs,proto3" json:"step_time_ms,omitempty"`
	DataloaderWaitMs float32                `protobuf:"fixed32,4,opt,name=dataloader_wait_ms,json=dataloaderWaitMs,proto3" json:"dataloader_wait_ms,omitempty"`
	CommExposedMs    float32                `protobuf:"fixed32,5,opt,name=comm_exposed_ms,json=commExposedMs,proto3" json:"comm_exposed_ms,omitempty"` // non-overlapped
	BubbleMs         float32                `protobuf:"fixed32,6,opt,name=bubble_ms,json=bubbleMs,proto3" json:"bubble_ms,omitempty"`                  // pipeline
	Mfu              float32                `protobuf:"fixed32,7,opt,name=mfu,proto3" json:"mfu,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrainingStep) Reset() {
	*x = TrainingStep{}
	mi := &file_nydux_runtime_v1_serving_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingStep) ProtoMessage() {}

func (x *TrainingStep) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_runtime_v1_serving_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingStep.ProtoReflect.Descriptor instead.
func (*TrainingStep) Descriptor() ([]byte, []int) {
	return file_nydux_runtime_v1_serving_proto_rawDescGZIP(), []int{2}
}

func (x *TrainingStep) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *TrainingStep) GetStep() uint64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *TrainingStep) GetStepTimeMs() float32 {
	if x != nil {
		return x.StepTimeMs
	}
	return 0
}

func (x *TrainingStep) GetDataloaderWaitMs() float32 {
	if x != nil {
		return x.DataloaderWaitMs
	}
	return 0
}

func (x *TrainingStep) GetCommExposedMs() float32 {
	if x != nil {
		return x.CommExposedMs
	}
	return 0
}

func (x *TrainingStep) GetBubbleMs() float32 {
	if x != nil {
		return x.BubbleMs
	}
	return 0
}

func (x *TrainingStep) GetMfu() float32 {
	if x != nil {
		return x.Mfu
	}
	return 0
}

var File_nydux_runtime_v1_serving_proto protoreflect.FileDescriptor

const file_nydux_runtime_v1_serving_proto_rawDesc = "" +
	"\n" +
	"\x1enydux/runtime/v1/serving.proto\x12\x10nydux.runtime.v1\x1a\x1bbuf/validate/validate.proto\"\xef\x01\n" +
	"\x0eServingMetrics\x12\x1f\n" +
	"\x06deploy\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06deploy\x12\x17\n" +
	"\attft_ms\x18\x02 \x01(\x02R\x06ttftMs\x12\x17\n" +
	"\atpot_ms\x18\x03 \x01(\x02R\x06tpotMs\x12\x14\n" +
	"\x05batch\x18\x04 \x01(\rR\x05batch\x12&\n" +
	"\x06kv_hit\x18\x05 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\x05kvHit\x12\x10\n" +
	"\x03req\x18\x06 \x01(\rR\x03req\x12\x1b\n" +
	"\ttokens_in\x18\a \x01(\x04R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\b \x01(\x04R\ttokensOut\"\x8d\x02\n" +
	"\x0eNcclCollective\x12\x10\n" +
	"\x03job\x18\x01 \x01(\tR\x03job\x12S\n" +
	"\x04kind\x18\x02 \x01(\tB?\xbaH<r:R\tallreduceR\tallgatherR\rreducescatterR\tbroadcastR\balltoallR\x04kind\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\x12\x1f\n" +
	"\vduration_us\x18\x04 \x01(\x02R\n" +
	"durationUs\x12\x1d\n" +
	"\n" +
	"busbw_gbps\x18\x05 \x01(\x02R\tbusbwGbps\x12\x14\n" +
	"\x05ranks\x18\x06 \x01(\rR\x05ranks\x12\x12\n" +
	"\x04algo\x18\a \x01(\tR\x04algo\x12\x14\n" +
	"\x05proto\x18\b \x01(\tR\x05proto\"\xec\x01\n" +
	"\fTrainingStep\x12\x10\n" +
	"\x03job\x18\x01 \x01(\tR\x03job\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x04R\x04step\x12 \n" +
	"\fstep_time_ms\x18\x03 \x01(\x02R\n" +
	"stepTimeMs\x12,\n" +
	"\x12dataloader_wait_ms\x18\x04 \x01(\x02R\x10dataloaderWaitMs\x12&\n" +
	"\x0fcomm_exposed_ms\x18\x05 \x01(\x02R\rcommExposedMs\x12\x1b\n" +
	"\tbubble_ms\x18\x06 \x01(\x02R\bbubbleMs\x12!\n" +
	"\x03mfu\x18\a \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\x03mfuB:Z8github.com/nydux/platform/api/nydux/runtime/v1;runtimev1b\x06proto3"

var (
	file_nydux_runtime_v1_serving_proto_rawDescOnce sync.Once
	file_nydux_runtime_v1_serving_proto_rawDescData []byte
)

func file_nydux_runtime_v1_serving_proto_rawDescGZIP() []byte {
	file_nydux_runtime_v1_serving_proto_rawDescOnce.Do(func() {
		file_nydux_runtime_v1_serving_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_runtime_v1_serving_proto_rawDesc), len(file_nydux_runtime_v1_serving_proto_rawDesc)))
	})
	return file_nydux_runtime_v1_serving_proto_rawDescData
}

var file_nydux_runtime_v1_serving_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nydux_runtime_v1_serving_proto_goTypes = []any{
	(*ServingMetrics)(nil), // 0: nydux.runtime.v1.ServingMetrics
	(*NcclCollective)(nil), // 1: nydux.runtime.v1.NcclCollective
	(*TrainingStep)(nil),   // 2: nydux.runtime.v1.TrainingStep
}
var file_nydux_runtime_v1_serving_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nydux_runtime_v1_serving_proto_init() }
func file_nydux_runtime_v1_serving_proto_init() {
	if File_nydux_runtime_v1_serving_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_runtime_v1_serving_proto_rawDesc), len(file_nydux_runtime_v1_serving_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nydux_runtime_v1_serving_proto_goTypes,
		DependencyIndexes: file_nydux_runtime_v1_serving_proto_depIdxs,
		MessageInfos:      file_nydux_runtime_v1_serving_proto_msgTypes,
	}.Build()
	File_nydux_runtime_v1_serving_proto = out.File
	file_nydux_runtime_v1_serving_proto_goTypes = nil
	file_nydux_runtime_v1_serving_proto_depIdxs = nil
}
