// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/policy/v1/policy.proto

package policyv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	SubjectKind   string                 `protobuf:"bytes,2,opt,name=subject_kind,json=subjectKind,proto3" json:"subject_kind,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,4,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // canonical JSON input document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_nydux_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_nydux_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *DecideRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *DecideRequest) GetSubjectKind() string {
	if x != nil {
		return x.SubjectKind
	}
	return ""
}

func (x *DecideRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *DecideRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion int32                  `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Reasons       []string               `protobuf:"bytes,4,rep,name=reasons,proto3" json:"reasons,omitempty"`
	LedgerSeq     int64                  `protobuf:"varint,5,opt,name=ledger_seq,json=ledgerSeq,proto3" json:"ledger_seq,omitempty"`
	DecidedAtNs   int64                  `protobuf:"varint,6,opt,name=decided_at_ns,json=decidedAtNs,proto3" json:"decided_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_nydux_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_nydux_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *Decision) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *Decision) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *Decision) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *Decision) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *Decision) GetLedgerSeq() int64 {
	if x != nil {
		return x.LedgerSeq
	}
	return 0
}

func (x *Decision) GetDecidedAtNs() int64 {
	if x != nil {
		return x.DecidedAtNs
	}
	return 0
}

type PolicyDecisionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      *Decision              `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	SubjectKind   string                 `protobuf:"bytes,2,opt,name=subject_kind,json=subjectKind,proto3" json:"subject_kind,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDecisionEvent) Reset() {
	*x = PolicyDecisionEvent{}
	mi := &file_nydux_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDecisionEvent) ProtoMessage() {}

func (x *PolicyDecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDecisionEvent.ProtoReflect.Descriptor instead.
func (*PolicyDecisionEvent) Descriptor() ([]byte, []int) {
	return file_nydux_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyDecisionEvent) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *PolicyDecisionEvent) GetSubjectKind() string {
	if x != nil {
		return x.SubjectKind
	}
	return ""
}

func (x *PolicyDecisionEvent) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

var File_nydux_policy_v1_policy_proto protoreflect.FileDescriptor

const file_nydux_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1cnydux/policy/v1/policy.proto\x12\x0fnydux.policy.v1\x1a\x1bbuf/validate/validate.proto\"\xcd\x01\n" +
	"\rDecideRequest\x12%\n" +
	"\tpolicy_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bpolicyId\x12W\n" +
	"\fsubject_kind\x18\x02 \x01(\tB4\xbaH1r/R\x0erecommendationR\ttoolchainR\x06deployR\n" +
	"agent_toolR\vsubjectKind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1d\n" +
	"\n" +
	"input_json\x18\x04 \x01(\fR\tinputJson\"\xe0\x01\n" +
	"\bDecision\x123\n" +
	"\averdict\x18\x01 \x01(\tB\x19\xbaH\x16r\x14R\x05allowR\x05blockR\x04warnR\averdict\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x05R\rpolicyVersion\x12\x18\n" +
	"\areasons\x18\x04 \x03(\tR\areasons\x12\x1d\n" +
	"\n" +
	"ledger_seq\x18\x05 \x01(\x03R\tledgerSeq\x12\"\n" +
	"\rdecided_at_ns\x18\x06 \x01(\x03R\vdecidedAtNs\"\x8e\x01\n" +
	"\x13PolicyDecisionEvent\x125\n" +
	"\bdecision\x18\x01 \x01(\v2\x19.nydux.policy.v1.DecisionR\bdecision\x12!\n" +
	"\fsubject_kind\x18\x02 \x01(\tR\vsubjectKind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId2T\n" +
	"\rPolicyService\x12C\n" +
	"\x06Decide\x12\x1e.nydux.policy.v1.DecideRequest\x1a\x19.nydux.policy.v1.DecisionB8Z6github.com/nydux/platform/api/nydux/policy/v1;policyv1b\x06proto3"

var (
	file_nydux_policy_v1_policy_proto_rawDescOnce sync.Once
	file_nydux_policy_v1_policy_proto_rawDescData []byte
)

func file_nydux_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_nydux_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_nydux_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_policy_v1_policy_proto_rawDesc), len(file_nydux_policy_v1_policy_proto_rawDesc)))
	})
	return file_nydux_policy_v1_policy_proto_rawDescData
}

var file_nydux_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nydux_policy_v1_policy_proto_goTypes = []any{
	(*DecideRequest)(nil),       // 0: nydux.policy.v1.DecideRequest
	(*Decision)(nil),            // 1: nydux.policy.v1.Decision
	(*PolicyDecisionEvent)(nil), // 2: nydux.policy.v1.PolicyDecisionEvent
}
var file_nydux_policy_v1_policy_proto_depIdxs = []int32{
	1, // 0: nydux.policy.v1.PolicyDecisionEvent.decision:type_name -> nydux.policy.v1.Decision
	0, // 1: nydux.policy.v1.PolicyService.Decide:input_type -> nydux.policy.v1.DecideRequest
	1, // 2: nydux.policy.v1.PolicyService.Decide:output_type -> nydux.policy.v1.Decision
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nydux_policy_v1_policy_proto_init() }
func file_nydux_policy_v1_policy_proto_init() {
	if File_nydux_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_policy_v1_policy_proto_rawDesc), len(file_nydux_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_nydux_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_nydux_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_nydux_policy_v1_policy_proto = out.File
	file_nydux_policy_v1_policy_proto_goTypes = nil
	file_nydux_policy_v1_policy_proto_depIdxs = nil
}
