// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nydux/twin/v1/twin.proto

package twinv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwinService_Simulate_FullMethodName = "/nydux.twin.v1.TwinService/Simulate"
)

// TwinServiceClient is the client API for TwinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwinServiceClient interface {
	Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (*SimulateResponse, error)
}

type twinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTwinServiceClient(cc grpc.ClientConnInterface) TwinServiceClient {
	return &twinServiceClient{cc}
}

func (c *twinServiceClient) Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (*SimulateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateResponse)
	err := c.cc.Invoke(ctx, TwinService_Simulate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwinServiceServer is the server API for TwinService service.
// All implementations must embed UnimplementedTwinServiceServer
// for forward compatibility.
type TwinServiceServer interface {
	Simulate(context.Context, *SimulateRequest) (*SimulateResponse, error)
	mustEmbedUnimplementedTwinServiceServer()
}

// UnimplementedTwinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwinServiceServer struct{}

func (UnimplementedTwinServiceServer) Simulate(context.Context, *SimulateRequest) (*SimulateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simulate not implemented")
}
func (UnimplementedTwinServiceServer) mustEmbedUnimplementedTwinServiceServer() {}
func (UnimplementedTwinServiceServer) testEmbeddedByValue()                     {}

// UnsafeTwinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwinServiceServer will
// result in compilation errors.
type UnsafeTwinServiceServer interface {
	mustEmbedUnimplementedTwinServiceServer()
}

func RegisterTwinServiceServer(s grpc.ServiceRegistrar, srv TwinServiceServer) {
	// If the following call pancis, it indicates UnimplementedTwinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwinService_ServiceDesc, srv)
}

func _TwinService_Simulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinServiceServer).Simulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwinService_Simulate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinServiceServer).Simulate(ctx, req.(*SimulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TwinService_ServiceDesc is the grpc.ServiceDesc for TwinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nydux.twin.v1.TwinService",
	HandlerType: (*TwinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simulate",
			Handler:    _TwinService_Simulate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nydux/twin/v1/twin.proto",
}
