// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/twin/v1/twin.proto

package twinv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parallelism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tp            uint32                 `protobuf:"varint,1,opt,name=tp,proto3" json:"tp,omitempty"`
	Pp            uint32                 `protobuf:"varint,2,opt,name=pp,proto3" json:"pp,omitempty"`
	Dp            uint32                 `protobuf:"varint,3,opt,name=dp,proto3" json:"dp,omitempty"`
	Ep            uint32                 `protobuf:"varint,4,opt,name=ep,proto3" json:"ep,omitempty"`
	MicroBatch    uint32                 `protobuf:"varint,5,opt,name=micro_batch,json=microBatch,proto3" json:"micro_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parallelism) Reset() {
	*x = Parallelism{}
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parallelism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parallelism) ProtoMessage() {}

func (x *Parallelism) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parallelism.ProtoReflect.Descriptor instead.
func (*Parallelism) Descriptor() ([]byte, []int) {
	return file_nydux_twin_v1_twin_proto_rawDescGZIP(), []int{0}
}

func (x *Parallelism) GetTp() uint32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *Parallelism) GetPp() uint32 {
	if x != nil {
		return x.Pp
	}
	return 0
}

func (x *Parallelism) GetDp() uint32 {
	if x != nil {
		return x.Dp
	}
	return 0
}

func (x *Parallelism) GetEp() uint32 {
	if x != nil {
		return x.Ep
	}
	return 0
}

func (x *Parallelism) GetMicroBatch() uint32 {
	if x != nil {
		return x.MicroBatch
	}
	return 0
}

type Scenario struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SnapshotRef string                 `protobuf:"bytes,1,opt,name=snapshot_ref,json=snapshotRef,proto3" json:"snapshot_ref,omitempty"`
	// exactly one mutation set per scenario (validated in service; proto3 optional semantics)
	GpuSku        string       `protobuf:"bytes,2,opt,name=gpu_sku,json=gpuSku,proto3" json:"gpu_sku,omitempty"`
	Parallelism   *Parallelism `protobuf:"bytes,3,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	ToolchainFp   string       `protobuf:"bytes,4,opt,name=toolchain_fp,json=toolchainFp,proto3" json:"toolchain_fp,omitempty"`
	Quantization  string       `protobuf:"bytes,5,opt,name=quantization,proto3" json:"quantization,omitempty"`
	NodeCount     uint32       `protobuf:"varint,6,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_nydux_twin_v1_twin_proto_rawDescGZIP(), []int{1}
}

func (x *Scenario) GetSnapshotRef() string {
	if x != nil {
		return x.SnapshotRef
	}
	return ""
}

func (x *Scenario) GetGpuSku() string {
	if x != nil {
		return x.GpuSku
	}
	return ""
}

func (x *Scenario) GetParallelism() *Parallelism {
	if x != nil {
		return x.Parallelism
	}
	return nil
}

func (x *Scenario) GetToolchainFp() string {
	if x != nil {
		return x.ToolchainFp
	}
	return ""
}

func (x *Scenario) GetQuantization() string {
	if x != nil {
		return x.Quantization
	}
	return ""
}

func (x *Scenario) GetNodeCount() uint32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

type Prediction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ScenarioIndex        uint32                 `protobuf:"varint,1,opt,name=scenario_index,json=scenarioIndex,proto3" json:"scenario_index,omitempty"`
	Throughput           float64                `protobuf:"fixed64,2,opt,name=throughput,proto3" json:"throughput,omitempty"`
	TtftMs               float64                `protobuf:"fixed64,3,opt,name=ttft_ms,json=ttftMs,proto3" json:"ttft_ms,omitempty"`
	TpotMs               float64                `protobuf:"fixed64,4,opt,name=tpot_ms,json=tpotMs,proto3" json:"tpot_ms,omitempty"`
	PowerW               float64                `protobuf:"fixed64,5,opt,name=power_w,json=powerW,proto3" json:"power_w,omitempty"`
	CostUsdMicrosPerHour int64                  `protobuf:"varint,6,opt,name=cost_usd_micros_per_hour,json=costUsdMicrosPerHour,proto3" json:"cost_usd_micros_per_hour,omitempty"`
	BandP10              float64                `protobuf:"fixed64,7,opt,name=band_p10,json=bandP10,proto3" json:"band_p10,omitempty"`
	BandP90              float64                `protobuf:"fixed64,8,opt,name=band_p90,json=bandP90,proto3" json:"band_p90,omitempty"`
	Support              string                 `protobuf:"bytes,9,opt,name=support,proto3" json:"support,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_nydux_twin_v1_twin_proto_rawDescGZIP(), []int{2}
}

func (x *Prediction) GetScenarioIndex() uint32 {
	if x != nil {
		return x.ScenarioIndex
	}
	return 0
}

func (x *Prediction) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *Prediction) GetTtftMs() float64 {
	if x != nil {
		return x.TtftMs
	}
	return 0
}

func (x *Prediction) GetTpotMs() float64 {
	if x != nil {
		return x.TpotMs
	}
	return 0
}

func (x *Prediction) GetPowerW() float64 {
	if x != nil {
		return x.PowerW
	}
	return 0
}

func (x *Prediction) GetCostUsdMicrosPerHour() int64 {
	if x != nil {
		return x.CostUsdMicrosPerHour
	}
	return 0
}

func (x *Prediction) GetBandP10() float64 {
	if x != nil {
		return x.BandP10
	}
	return 0
}

func (x *Prediction) GetBandP90() float64 {
	if x != nil {
		return x.BandP90
	}
	return 0
}

func (x *Prediction) GetSupport() string {
	if x != nil {
		return x.Support
	}
	return ""
}

type SimulateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*Scenario            `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateRequest) Reset() {
	*x = SimulateRequest{}
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRequest) ProtoMessage() {}

func (x *SimulateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRequest.ProtoReflect.Descriptor instead.
func (*SimulateRequest) Descriptor() ([]byte, []int) {
	return file_nydux_twin_v1_twin_proto_rawDescGZIP(), []int{3}
}

func (x *SimulateRequest) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

type SimulateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateResponse) Reset() {
	*x = SimulateResponse{}
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateResponse) ProtoMessage() {}

func (x *SimulateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_twin_v1_twin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateResponse.ProtoReflect.Descriptor instead.
func (*SimulateResponse) Descriptor() ([]byte, []int) {
	return file_nydux_twin_v1_twin_proto_rawDescGZIP(), []int{4}
}

func (x *SimulateResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_nydux_twin_v1_twin_proto protoreflect.FileDescriptor

const file_nydux_twin_v1_twin_proto_rawDesc = "" +
	"\n" +
	"\x18nydux/twin/v1/twin.proto\x12\rnydux.twin.v1\x1a\x1bbuf/validate/validate.proto\"\x89\x01\n" +
	"\vParallelism\x12\x17\n" +
	"\x02tp\x18\x01 \x01(\rB\a\xbaH\x04*\x02(\x01R\x02tp\x12\x17\n" +
	"\x02pp\x18\x02 \x01(\rB\a\xbaH\x04*\x02(\x01R\x02pp\x12\x17\n" +
	"\x02dp\x18\x03 \x01(\rB\a\xbaH\x04*\x02(\x01R\x02dp\x12\x0e\n" +
	"\x02ep\x18\x04 \x01(\rR\x02ep\x12\x1f\n" +
	"\vmicro_batch\x18\x05 \x01(\rR\n" +
	"microBatch\"\x8d\x02\n" +
	"\bScenario\x12*\n" +
	"\fsnapshot_ref\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vsnapshotRef\x12\x17\n" +
	"\agpu_sku\x18\x02 \x01(\tR\x06gpuSku\x12<\n" +
	"\vparallelism\x18\x03 \x01(\v2\x1a.nydux.twin.v1.ParallelismR\vparallelism\x12!\n" +
	"\ftoolchain_fp\x18\x04 \x01(\tR\vtoolchainFp\x12<\n" +
	"\fquantization\x18\x05 \x01(\tB\x18\xbaH\x15r\x13R\x00R\x04bf16R\x03fp8R\x04int4R\fquantization\x12\x1d\n" +
	"\n" +
	"node_count\x18\x06 \x01(\rR\tnodeCount\"\xc0\x02\n" +
	"\n" +
	"Prediction\x12%\n" +
	"\x0escenario_index\x18\x01 \x01(\rR\rscenarioIndex\x12\x1e\n" +
	"\n" +
	"throughput\x18\x02 \x01(\x01R\n" +
	"throughput\x12\x17\n" +
	"\attft_ms\x18\x03 \x01(\x01R\x06ttftMs\x12\x17\n" +
	"\atpot_ms\x18\x04 \x01(\x01R\x06tpotMs\x12\x17\n" +
	"\apower_w\x18\x05 \x01(\x01R\x06powerW\x126\n" +
	"\x18cost_usd_micros_per_hour\x18\x06 \x01(\x03R\x14costUsdMicrosPerHour\x12\x19\n" +
	"\bband_p10\x18\a \x01(\x01R\abandP10\x12\x19\n" +
	"\bband_p90\x18\b \x01(\x01R\abandP90\x122\n" +
	"\asupport\x18\t \x01(\tB\x18\xbaH\x15r\x13R\x04FULLR\vLOW_SUPPORTR\asupport\"U\n" +
	"\x0fSimulateRequest\x12B\n" +
	"\tscenarios\x18\x01 \x03(\v2\x17.nydux.twin.v1.ScenarioB\v\xbaH\b\x92\x01\x05\b\x01\x10\xc8\x01R\tscenarios\")\n" +
	"\x10SimulateResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2Z\n" +
	"\vTwinService\x12K\n" +
	"\bSimulate\x12\x1e.nydux.twin.v1.SimulateRequest\x1a\x1f.nydux.twin.v1.SimulateResponseB4Z2github.com/nydux/platform/api/nydux/twin/v1;twinv1b\x06proto3"

var (
	file_nydux_twin_v1_twin_proto_rawDescOnce sync.Once
	file_nydux_twin_v1_twin_proto_rawDescData []byte
)

func file_nydux_twin_v1_twin_proto_rawDescGZIP() []byte {
	file_nydux_twin_v1_twin_proto_rawDescOnce.Do(func() {
		file_nydux_twin_v1_twin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_twin_v1_twin_proto_rawDesc), len(file_nydux_twin_v1_twin_proto_rawDesc)))
	})
	return file_nydux_twin_v1_twin_proto_rawDescData
}

var file_nydux_twin_v1_twin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nydux_twin_v1_twin_proto_goTypes = []any{
	(*Parallelism)(nil),      // 0: nydux.twin.v1.Parallelism
	(*Scenario)(nil),         // 1: nydux.twin.v1.Scenario
	(*Prediction)(nil),       // 2: nydux.twin.v1.Prediction
	(*SimulateRequest)(nil),  // 3: nydux.twin.v1.SimulateRequest
	(*SimulateResponse)(nil), // 4: nydux.twin.v1.SimulateResponse
}
var file_nydux_twin_v1_twin_proto_depIdxs = []int32{
	0, // 0: nydux.twin.v1.Scenario.parallelism:type_name -> nydux.twin.v1.Parallelism
	1, // 1: nydux.twin.v1.SimulateRequest.scenarios:type_name -> nydux.twin.v1.Scenario
	3, // 2: nydux.twin.v1.TwinService.Simulate:input_type -> nydux.twin.v1.SimulateRequest
	4, // 3: nydux.twin.v1.TwinService.Simulate:output_type -> nydux.twin.v1.SimulateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nydux_twin_v1_twin_proto_init() }
func file_nydux_twin_v1_twin_proto_init() {
	if File_nydux_twin_v1_twin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_twin_v1_twin_proto_rawDesc), len(file_nydux_twin_v1_twin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_twin_v1_twin_proto_goTypes,
		DependencyIndexes: file_nydux_twin_v1_twin_proto_depIdxs,
		MessageInfos:      file_nydux_twin_v1_twin_proto_msgTypes,
	}.Build()
	File_nydux_twin_v1_twin_proto = out.File
	file_nydux_twin_v1_twin_proto_goTypes = nil
	file_nydux_twin_v1_twin_proto_depIdxs = nil
}
