// proto/nydux/finance/v1/cost.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/finance/v1/cost.proto

package financev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CostCalculated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	UsdMicros     int64                  `protobuf:"varint,2,opt,name=usd_micros,json=usdMicros,proto3" json:"usd_micros,omitempty"`
	Basis         string                 `protobuf:"bytes,3,opt,name=basis,proto3" json:"basis,omitempty"`
	WindowStartNs int64                  `protobuf:"varint,4,opt,name=window_start_ns,json=windowStartNs,proto3" json:"window_start_ns,omitempty"`
	WindowEndNs   int64                  `protobuf:"varint,5,opt,name=window_end_ns,json=windowEndNs,proto3" json:"window_end_ns,omitempty"`
	TeamId        string                 `protobuf:"bytes,6,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	WorkloadId    string                 `protobuf:"bytes,8,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,9,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostCalculated) Reset() {
	*x = CostCalculated{}
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostCalculated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostCalculated) ProtoMessage() {}

func (x *CostCalculated) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostCalculated.ProtoReflect.Descriptor instead.
func (*CostCalculated) Descriptor() ([]byte, []int) {
	return file_nydux_finance_v1_cost_proto_rawDescGZIP(), []int{0}
}

func (x *CostCalculated) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CostCalculated) GetUsdMicros() int64 {
	if x != nil {
		return x.UsdMicros
	}
	return 0
}

func (x *CostCalculated) GetBasis() string {
	if x != nil {
		return x.Basis
	}
	return ""
}

func (x *CostCalculated) GetWindowStartNs() int64 {
	if x != nil {
		return x.WindowStartNs
	}
	return 0
}

func (x *CostCalculated) GetWindowEndNs() int64 {
	if x != nil {
		return x.WindowEndNs
	}
	return 0
}

func (x *CostCalculated) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CostCalculated) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CostCalculated) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *CostCalculated) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type SavingsReported struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Period               string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`                                       // YYYY-MM
	TwinUsdMicros        int64                  `protobuf:"varint,2,opt,name=twin_usd_micros,json=twinUsdMicros,proto3" json:"twin_usd_micros,omitempty"` // may be negative (honesty rule, RFC-004 4.3)
	TrailingUsdMicros    int64                  `protobuf:"varint,3,opt,name=trailing_usd_micros,json=trailingUsdMicros,proto3" json:"trailing_usd_micros,omitempty"`
	ContractualUsdMicros int64                  `protobuf:"varint,4,opt,name=contractual_usd_micros,json=contractualUsdMicros,proto3" json:"contractual_usd_micros,omitempty"` // = min(twin, trailing), floored per line item
	BaselineId           string                 `protobuf:"bytes,5,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	BaselineVersion      int32                  `protobuf:"varint,6,opt,name=baseline_version,json=baselineVersion,proto3" json:"baseline_version,omitempty"`
	MethodDocUri         string                 `protobuf:"bytes,7,opt,name=method_doc_uri,json=methodDocUri,proto3" json:"method_doc_uri,omitempty"` // replay-bundle reference
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SavingsReported) Reset() {
	*x = SavingsReported{}
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavingsReported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavingsReported) ProtoMessage() {}

func (x *SavingsReported) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavingsReported.ProtoReflect.Descriptor instead.
func (*SavingsReported) Descriptor() ([]byte, []int) {
	return file_nydux_finance_v1_cost_proto_rawDescGZIP(), []int{1}
}

func (x *SavingsReported) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *SavingsReported) GetTwinUsdMicros() int64 {
	if x != nil {
		return x.TwinUsdMicros
	}
	return 0
}

func (x *SavingsReported) GetTrailingUsdMicros() int64 {
	if x != nil {
		return x.TrailingUsdMicros
	}
	return 0
}

func (x *SavingsReported) GetContractualUsdMicros() int64 {
	if x != nil {
		return x.ContractualUsdMicros
	}
	return 0
}

func (x *SavingsReported) GetBaselineId() string {
	if x != nil {
		return x.BaselineId
	}
	return ""
}

func (x *SavingsReported) GetBaselineVersion() int32 {
	if x != nil {
		return x.BaselineVersion
	}
	return 0
}

func (x *SavingsReported) GetMethodDocUri() string {
	if x != nil {
		return x.MethodDocUri
	}
	return ""
}

type BaselineReanchored struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaselineId        string                 `protobuf:"bytes,1,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"`
	NewVersion        int32                  `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CosignCustomerSig string                 `protobuf:"bytes,4,opt,name=cosign_customer_sig,json=cosignCustomerSig,proto3" json:"cosign_customer_sig,omitempty"`
	CosignNyduxSig    string                 `protobuf:"bytes,5,opt,name=cosign_nydux_sig,json=cosignNyduxSig,proto3" json:"cosign_nydux_sig,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaselineReanchored) Reset() {
	*x = BaselineReanchored{}
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineReanchored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineReanchored) ProtoMessage() {}

func (x *BaselineReanchored) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineReanchored.ProtoReflect.Descriptor instead.
func (*BaselineReanchored) Descriptor() ([]byte, []int) {
	return file_nydux_finance_v1_cost_proto_rawDescGZIP(), []int{2}
}

func (x *BaselineReanchored) GetBaselineId() string {
	if x != nil {
		return x.BaselineId
	}
	return ""
}

func (x *BaselineReanchored) GetNewVersion() int32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *BaselineReanchored) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BaselineReanchored) GetCosignCustomerSig() string {
	if x != nil {
		return x.CosignCustomerSig
	}
	return ""
}

func (x *BaselineReanchored) GetCosignNyduxSig() string {
	if x != nil {
		return x.CosignNyduxSig
	}
	return ""
}

type GetAttributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dim           string                 `protobuf:"bytes,1,opt,name=dim,proto3" json:"dim,omitempty"`
	FromNs        int64                  `protobuf:"varint,2,opt,name=from_ns,json=fromNs,proto3" json:"from_ns,omitempty"`
	ToNs          int64                  `protobuf:"varint,3,opt,name=to_ns,json=toNs,proto3" json:"to_ns,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributionRequest) Reset() {
	*x = GetAttributionRequest{}
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributionRequest) ProtoMessage() {}

func (x *GetAttributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributionRequest.ProtoReflect.Descriptor instead.
func (*GetAttributionRequest) Descriptor() ([]byte, []int) {
	return file_nydux_finance_v1_cost_proto_rawDescGZIP(), []int{3}
}

func (x *GetAttributionRequest) GetDim() string {
	if x != nil {
		return x.Dim
	}
	return ""
}

func (x *GetAttributionRequest) GetFromNs() int64 {
	if x != nil {
		return x.FromNs
	}
	return 0
}

func (x *GetAttributionRequest) GetToNs() int64 {
	if x != nil {
		return x.ToNs
	}
	return 0
}

func (x *GetAttributionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAttributionRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type AttributionRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // team_id | model_id | workload_id | kernel_hash | "token"
	UsdMicros     int64                  `protobuf:"varint,2,opt,name=usd_micros,json=usdMicros,proto3" json:"usd_micros,omitempty"`
	GpuHours      float64                `protobuf:"fixed64,3,opt,name=gpu_hours,json=gpuHours,proto3" json:"gpu_hours,omitempty"`
	Tokens        int64                  `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributionRow) Reset() {
	*x = AttributionRow{}
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributionRow) ProtoMessage() {}

func (x *AttributionRow) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributionRow.ProtoReflect.Descriptor instead.
func (*AttributionRow) Descriptor() ([]byte, []int) {
	return file_nydux_finance_v1_cost_proto_rawDescGZIP(), []int{4}
}

func (x *AttributionRow) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributionRow) GetUsdMicros() int64 {
	if x != nil {
		return x.UsdMicros
	}
	return 0
}

func (x *AttributionRow) GetGpuHours() float64 {
	if x != nil {
		return x.GpuHours
	}
	return 0
}

func (x *AttributionRow) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type GetAttributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AttributionRow      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Completeness  float64                `protobuf:"fixed64,3,opt,name=completeness,proto3" json:"completeness,omitempty"` // parked-slice awareness
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributionResponse) Reset() {
	*x = GetAttributionResponse{}
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributionResponse) ProtoMessage() {}

func (x *GetAttributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_finance_v1_cost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributionResponse.ProtoReflect.Descriptor instead.
func (*GetAttributionResponse) Descriptor() ([]byte, []int) {
	return file_nydux_finance_v1_cost_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttributionResponse) GetItems() []*AttributionRow {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetAttributionResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetAttributionResponse) GetCompleteness() float64 {
	if x != nil {
		return x.Completeness
	}
	return 0
}

var File_nydux_finance_v1_cost_proto protoreflect.FileDescriptor

const file_nydux_finance_v1_cost_proto_rawDesc = "" +
	"\n" +
	"\x1bnydux/finance/v1/cost.proto\x12\x10nydux.finance.v1\x1a\x1bbuf/validate/validate.proto\"\xdd\x02\n" +
	"\x0eCostCalculated\x12#\n" +
	"\bslice_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\asliceId\x12&\n" +
	"\n" +
	"usd_micros\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\tusdMicros\x12>\n" +
	"\x05basis\x18\x03 \x01(\tB(\xbaH%r#R\bondemandR\x06commitR\x04spotR\tamortizedR\x05basis\x12&\n" +
	"\x0fwindow_start_ns\x18\x04 \x01(\x03R\rwindowStartNs\x12\"\n" +
	"\rwindow_end_ns\x18\x05 \x01(\x03R\vwindowEndNs\x12\x17\n" +
	"\ateam_id\x18\x06 \x01(\tR\x06teamId\x12\x19\n" +
	"\bmodel_id\x18\a \x01(\tR\amodelId\x12\x1f\n" +
	"\vworkload_id\x18\b \x01(\tR\n" +
	"workloadId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\t \x01(\tR\tclusterId\"\xcf\x02\n" +
	"\x0fSavingsReported\x122\n" +
	"\x06period\x18\x01 \x01(\tB\x1a\xbaH\x17r\x152\x13^[0-9]{4}-[0-9]{2}$R\x06period\x12&\n" +
	"\x0ftwin_usd_micros\x18\x02 \x01(\x03R\rtwinUsdMicros\x12.\n" +
	"\x13trailing_usd_micros\x18\x03 \x01(\x03R\x11trailingUsdMicros\x124\n" +
	"\x16contractual_usd_micros\x18\x04 \x01(\x03R\x14contractualUsdMicros\x12)\n" +
	"\vbaseline_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"baselineId\x12)\n" +
	"\x10baseline_version\x18\x06 \x01(\x05R\x0fbaselineVersion\x12$\n" +
	"\x0emethod_doc_uri\x18\a \x01(\tR\fmethodDocUri\"\xd1\x01\n" +
	"\x12BaselineReanchored\x12\x1f\n" +
	"\vbaseline_id\x18\x01 \x01(\tR\n" +
	"baselineId\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x05R\n" +
	"newVersion\x12\x1f\n" +
	"\x06reason\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\bR\x06reason\x12.\n" +
	"\x13cosign_customer_sig\x18\x04 \x01(\tR\x11cosignCustomerSig\x12(\n" +
	"\x10cosign_nydux_sig\x18\x05 \x01(\tR\x0ecosignNyduxSig\"\xbe\x01\n" +
	"\x15GetAttributionRequest\x12=\n" +
	"\x03dim\x18\x01 \x01(\tB+\xbaH(r&R\x04teamR\x05modelR\bworkloadR\x06kernelR\x05tokenR\x03dim\x12\x17\n" +
	"\afrom_ns\x18\x02 \x01(\x03R\x06fromNs\x12\x13\n" +
	"\x05to_ns\x18\x03 \x01(\x03R\x04toNs\x12 \n" +
	"\x05limit\x18\x04 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x01R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"v\n" +
	"\x0eAttributionRow\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"usd_micros\x18\x02 \x01(\x03R\tusdMicros\x12\x1b\n" +
	"\tgpu_hours\x18\x03 \x01(\x01R\bgpuHours\x12\x16\n" +
	"\x06tokens\x18\x04 \x01(\x03R\x06tokens\"\xae\x01\n" +
	"\x16GetAttributionResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .nydux.finance.v1.AttributionRowR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12;\n" +
	"\fcompleteness\x18\x03 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\fcompleteness2u\n" +
	"\x0eFinanceService\x12c\n" +
	"\x0eGetAttribution\x12'.nydux.finance.v1.GetAttributionRequest\x1a(.nydux.finance.v1.GetAttributionResponseB:Z8github.com/nydux/platform/api/nydux/finance/v1;financev1b\x06proto3"

var (
	file_nydux_finance_v1_cost_proto_rawDescOnce sync.Once
	file_nydux_finance_v1_cost_proto_rawDescData []byte
)

func file_nydux_finance_v1_cost_proto_rawDescGZIP() []byte {
	file_nydux_finance_v1_cost_proto_rawDescOnce.Do(func() {
		file_nydux_finance_v1_cost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_finance_v1_cost_proto_rawDesc), len(file_nydux_finance_v1_cost_proto_rawDesc)))
	})
	return file_nydux_finance_v1_cost_proto_rawDescData
}

var file_nydux_finance_v1_cost_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nydux_finance_v1_cost_proto_goTypes = []any{
	(*CostCalculated)(nil),         // 0: nydux.finance.v1.CostCalculated
	(*SavingsReported)(nil),        // 1: nydux.finance.v1.SavingsReported
	(*BaselineReanchored)(nil),     // 2: nydux.finance.v1.BaselineReanchored
	(*GetAttributionRequest)(nil),  // 3: nydux.finance.v1.GetAttributionRequest
	(*AttributionRow)(nil),         // 4: nydux.finance.v1.AttributionRow
	(*GetAttributionResponse)(nil), // 5: nydux.finance.v1.GetAttributionResponse
}
var file_nydux_finance_v1_cost_proto_depIdxs = []int32{
	4, // 0: nydux.finance.v1.GetAttributionResponse.items:type_name -> nydux.finance.v1.AttributionRow
	3, // 1: nydux.finance.v1.FinanceService.GetAttribution:input_type -> nydux.finance.v1.GetAttributionRequest
	5, // 2: nydux.finance.v1.FinanceService.GetAttribution:output_type -> nydux.finance.v1.GetAttributionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nydux_finance_v1_cost_proto_init() }
func file_nydux_finance_v1_cost_proto_init() {
	if File_nydux_finance_v1_cost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_finance_v1_cost_proto_rawDesc), len(file_nydux_finance_v1_cost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_finance_v1_cost_proto_goTypes,
		DependencyIndexes: file_nydux_finance_v1_cost_proto_depIdxs,
		MessageInfos:      file_nydux_finance_v1_cost_proto_msgTypes,
	}.Build()
	File_nydux_finance_v1_cost_proto = out.File
	file_nydux_finance_v1_cost_proto_goTypes = nil
	file_nydux_finance_v1_cost_proto_depIdxs = nil
}
