// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/gateway/v1/ingest.proto

package gatewayv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/nydux/platform/api/nydux/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*v1.EventEnvelope    `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	SpoolId       string                 `protobuf:"bytes,2,opt,name=spool_id,json=spoolId,proto3" json:"spool_id,omitempty"` // set on link-recovery replay
	Replay        bool                   `protobuf:"varint,3,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBatch) Reset() {
	*x = SubmitBatch{}
	mi := &file_nydux_gateway_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatch) ProtoMessage() {}

func (x *SubmitBatch) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_gateway_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatch.ProtoReflect.Descriptor instead.
func (*SubmitBatch) Descriptor() ([]byte, []int) {
	return file_nydux_gateway_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitBatch) GetEnvelopes() []*v1.EventEnvelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

func (x *SubmitBatch) GetSpoolId() string {
	if x != nil {
		return x.SpoolId
	}
	return ""
}

func (x *SubmitBatch) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

type SubmitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      uint32                 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Rejects       []*RejectDetail        `protobuf:"bytes,3,rep,name=rejects,proto3" json:"rejects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAck) Reset() {
	*x = SubmitAck{}
	mi := &file_nydux_gateway_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAck) ProtoMessage() {}

func (x *SubmitAck) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_gateway_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAck.ProtoReflect.Descriptor instead.
func (*SubmitAck) Descriptor() ([]byte, []int) {
	return file_nydux_gateway_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAck) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *SubmitAck) GetRejected() uint32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *SubmitAck) GetRejects() []*RejectDetail {
	if x != nil {
		return x.Rejects
	}
	return nil
}

type RejectDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"` // for privacy_filter: offending field path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectDetail) Reset() {
	*x = RejectDetail{}
	mi := &file_nydux_gateway_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectDetail) ProtoMessage() {}

func (x *RejectDetail) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_gateway_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectDetail.ProtoReflect.Descriptor instead.
func (*RejectDetail) Descriptor() ([]byte, []int) {
	return file_nydux_gateway_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *RejectDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RejectDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var File_nydux_gateway_v1_ingest_proto protoreflect.FileDescriptor

const file_nydux_gateway_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1dnydux/gateway/v1/ingest.proto\x12\x10nydux.gateway.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1enydux/common/v1/envelope.proto\"\x8b\x01\n" +
	"\vSubmitBatch\x12I\n" +
	"\tenvelopes\x18\x01 \x03(\v2\x1e.nydux.common.v1.EventEnvelopeB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\tenvelopes\x12\x19\n" +
	"\bspool_id\x18\x02 \x01(\tR\aspoolId\x12\x16\n" +
	"\x06replay\x18\x03 \x01(\bR\x06replay\"}\n" +
	"\tSubmitAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\rR\brejected\x128\n" +
	"\arejects\x18\x03 \x03(\v2\x1e.nydux.gateway.v1.RejectDetailR\arejects\"\x98\x01\n" +
	"\fRejectDetail\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12W\n" +
	"\x06reason\x18\x02 \x01(\tB?\xbaH<r:R\x0eprivacy_filterR\x0eschema_unknownR\x0fvalidate_failedR\atoo_oldR\x06reason\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field2Y\n" +
	"\rIngestService\x12H\n" +
	"\x06Submit\x12\x1d.nydux.gateway.v1.SubmitBatch\x1a\x1b.nydux.gateway.v1.SubmitAck(\x010\x01B:Z8github.com/nydux/platform/api/nydux/gateway/v1;gatewayv1b\x06proto3"

var (
	file_nydux_gateway_v1_ingest_proto_rawDescOnce sync.Once
	file_nydux_gateway_v1_ingest_proto_rawDescData []byte
)

func file_nydux_gateway_v1_ingest_proto_rawDescGZIP() []byte {
	file_nydux_gateway_v1_ingest_proto_rawDescOnce.Do(func() {
		file_nydux_gateway_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_gateway_v1_ingest_proto_rawDesc), len(file_nydux_gateway_v1_ingest_proto_rawDesc)))
	})
	return file_nydux_gateway_v1_ingest_proto_rawDescData
}

var file_nydux_gateway_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nydux_gateway_v1_ingest_proto_goTypes = []any{
	(*SubmitBatch)(nil),      // 0: nydux.gateway.v1.SubmitBatch
	(*SubmitAck)(nil),        // 1: nydux.gateway.v1.SubmitAck
	(*RejectDetail)(nil),     // 2: nydux.gateway.v1.RejectDetail
	(*v1.EventEnvelope)(nil), // 3: nydux.common.v1.EventEnvelope
}
var file_nydux_gateway_v1_ingest_proto_depIdxs = []int32{
	3, // 0: nydux.gateway.v1.SubmitBatch.envelopes:type_name -> nydux.common.v1.EventEnvelope
	2, // 1: nydux.gateway.v1.SubmitAck.rejects:type_name -> nydux.gateway.v1.RejectDetail
	0, // 2: nydux.gateway.v1.IngestService.Submit:input_type -> nydux.gateway.v1.SubmitBatch
	1, // 3: nydux.gateway.v1.IngestService.Submit:output_type -> nydux.gateway.v1.SubmitAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nydux_gateway_v1_ingest_proto_init() }
func file_nydux_gateway_v1_ingest_proto_init() {
	if File_nydux_gateway_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_gateway_v1_ingest_proto_rawDesc), len(file_nydux_gateway_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_gateway_v1_ingest_proto_goTypes,
		DependencyIndexes: file_nydux_gateway_v1_ingest_proto_depIdxs,
		MessageInfos:      file_nydux_gateway_v1_ingest_proto_msgTypes,
	}.Build()
	File_nydux_gateway_v1_ingest_proto = out.File
	file_nydux_gateway_v1_ingest_proto_goTypes = nil
	file_nydux_gateway_v1_ingest_proto_depIdxs = nil
}
