// proto/nydux/compiler/v1/kernel.proto
// Compiler-layer wire contracts: kernels, scores, regressions.
// Extends RFC-002 / ECD-003 §3.2. Message field numbers FROZEN once merged.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nydux/compiler/v1/kernel.proto

package compilerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelService_GetKernel_FullMethodName    = "/nydux.compiler.v1.KernelService/GetKernel"
	KernelService_ListKernels_FullMethodName  = "/nydux.compiler.v1.KernelService/ListKernels"
	KernelService_StreamScores_FullMethodName = "/nydux.compiler.v1.KernelService/StreamScores"
)

// KernelServiceClient is the client API for KernelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KernelServiceClient interface {
	GetKernel(ctx context.Context, in *GetKernelRequest, opts ...grpc.CallOption) (*Kernel, error)
	ListKernels(ctx context.Context, in *ListKernelsRequest, opts ...grpc.CallOption) (*ListKernelsResponse, error)
	StreamScores(ctx context.Context, in *ListKernelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KernelScored], error)
}

type kernelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelServiceClient(cc grpc.ClientConnInterface) KernelServiceClient {
	return &kernelServiceClient{cc}
}

func (c *kernelServiceClient) GetKernel(ctx context.Context, in *GetKernelRequest, opts ...grpc.CallOption) (*Kernel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Kernel)
	err := c.cc.Invoke(ctx, KernelService_GetKernel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ListKernels(ctx context.Context, in *ListKernelsRequest, opts ...grpc.CallOption) (*ListKernelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKernelsResponse)
	err := c.cc.Invoke(ctx, KernelService_ListKernels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) StreamScores(ctx context.Context, in *ListKernelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KernelScored], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelService_ServiceDesc.Streams[0], KernelService_StreamScores_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListKernelsRequest, KernelScored]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_StreamScoresClient = grpc.ServerStreamingClient[KernelScored]

// KernelServiceServer is the server API for KernelService service.
// All implementations must embed UnimplementedKernelServiceServer
// for forward compatibility.
type KernelServiceServer interface {
	GetKernel(context.Context, *GetKernelRequest) (*Kernel, error)
	ListKernels(context.Context, *ListKernelsRequest) (*ListKernelsResponse, error)
	StreamScores(*ListKernelsRequest, grpc.ServerStreamingServer[KernelScored]) error
	mustEmbedUnimplementedKernelServiceServer()
}

// UnimplementedKernelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelServiceServer struct{}

func (UnimplementedKernelServiceServer) GetKernel(context.Context, *GetKernelRequest) (*Kernel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKernel not implemented")
}
func (UnimplementedKernelServiceServer) ListKernels(context.Context, *ListKernelsRequest) (*ListKernelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKernels not implemented")
}
func (UnimplementedKernelServiceServer) StreamScores(*ListKernelsRequest, grpc.ServerStreamingServer[KernelScored]) error {
	return status.Errorf(codes.Unimplemented, "method StreamScores not implemented")
}
func (UnimplementedKernelServiceServer) mustEmbedUnimplementedKernelServiceServer() {}
func (UnimplementedKernelServiceServer) testEmbeddedByValue()                       {}

// UnsafeKernelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServiceServer will
// result in compilation errors.
type UnsafeKernelServiceServer interface {
	mustEmbedUnimplementedKernelServiceServer()
}

func RegisterKernelServiceServer(s grpc.ServiceRegistrar, srv KernelServiceServer) {
	// If the following call pancis, it indicates UnimplementedKernelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelService_ServiceDesc, srv)
}

func _KernelService_GetKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GetKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GetKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GetKernel(ctx, req.(*GetKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ListKernels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKernelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ListKernels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ListKernels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ListKernels(ctx, req.(*ListKernelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_StreamScores_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListKernelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServiceServer).StreamScores(m, &grpc.GenericServerStream[ListKernelsRequest, KernelScored]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_StreamScoresServer = grpc.ServerStreamingServer[KernelScored]

// KernelService_ServiceDesc is the grpc.ServiceDesc for KernelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nydux.compiler.v1.KernelService",
	HandlerType: (*KernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKernel",
			Handler:    _KernelService_GetKernel_Handler,
		},
		{
			MethodName: "ListKernels",
			Handler:    _KernelService_ListKernels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamScores",
			Handler:       _KernelService_StreamScores_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nydux/compiler/v1/kernel.proto",
}

const (
	RegressionService_CheckRegressions_FullMethodName = "/nydux.compiler.v1.RegressionService/CheckRegressions"
)

// RegressionServiceClient is the client API for RegressionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegressionServiceClient interface {
	CheckRegressions(ctx context.Context, in *CheckRegressionsRequest, opts ...grpc.CallOption) (*CheckRegressionsResponse, error)
}

type regressionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegressionServiceClient(cc grpc.ClientConnInterface) RegressionServiceClient {
	return &regressionServiceClient{cc}
}

func (c *regressionServiceClient) CheckRegressions(ctx context.Context, in *CheckRegressionsRequest, opts ...grpc.CallOption) (*CheckRegressionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRegressionsResponse)
	err := c.cc.Invoke(ctx, RegressionService_CheckRegressions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegressionServiceServer is the server API for RegressionService service.
// All implementations must embed UnimplementedRegressionServiceServer
// for forward compatibility.
type RegressionServiceServer interface {
	CheckRegressions(context.Context, *CheckRegressionsRequest) (*CheckRegressionsResponse, error)
	mustEmbedUnimplementedRegressionServiceServer()
}

// UnimplementedRegressionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegressionServiceServer struct{}

func (UnimplementedRegressionServiceServer) CheckRegressions(context.Context, *CheckRegressionsRequest) (*CheckRegressionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRegressions not implemented")
}
func (UnimplementedRegressionServiceServer) mustEmbedUnimplementedRegressionServiceServer() {}
func (UnimplementedRegressionServiceServer) testEmbeddedByValue()                           {}

// UnsafeRegressionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegressionServiceServer will
// result in compilation errors.
type UnsafeRegressionServiceServer interface {
	mustEmbedUnimplementedRegressionServiceServer()
}

func RegisterRegressionServiceServer(s grpc.ServiceRegistrar, srv RegressionServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegressionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegressionService_ServiceDesc, srv)
}

func _RegressionService_CheckRegressions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRegressionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegressionServiceServer).CheckRegressions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegressionService_CheckRegressions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegressionServiceServer).CheckRegressions(ctx, req.(*CheckRegressionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegressionService_ServiceDesc is the grpc.ServiceDesc for RegressionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegressionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nydux.compiler.v1.RegressionService",
	HandlerType: (*RegressionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRegressions",
			Handler:    _RegressionService_CheckRegressions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nydux/compiler/v1/kernel.proto",
}
