// proto/nydux/compiler/v1/kernel.proto
// Compiler-layer wire contracts: kernels, scores, regressions.
// Extends RFC-002 / ECD-003 §3.2. Message field numbers FROZEN once merged.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/compiler/v1/kernel.proto

package compilerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KernelStatus int32

const (
	KernelStatus_KERNEL_STATUS_UNSPECIFIED      KernelStatus = 0
	KernelStatus_KERNEL_STATUS_SCORED           KernelStatus = 1 // dynamic KES (NCU-joined)
	KernelStatus_KERNEL_STATUS_STATIC_ESTIMATE  KernelStatus = 2 // static-only KES, confidence in [0.4,0.6]
	KernelStatus_KERNEL_STATUS_MEASUREMENT_ONLY KernelStatus = 3 // unknown IR version / parser miss
)

// Enum value maps for KernelStatus.
var (
	KernelStatus_name = map[int32]string{
		0: "KERNEL_STATUS_UNSPECIFIED",
		1: "KERNEL_STATUS_SCORED",
		2: "KERNEL_STATUS_STATIC_ESTIMATE",
		3: "KERNEL_STATUS_MEASUREMENT_ONLY",
	}
	KernelStatus_value = map[string]int32{
		"KERNEL_STATUS_UNSPECIFIED":      0,
		"KERNEL_STATUS_SCORED":           1,
		"KERNEL_STATUS_STATIC_ESTIMATE":  2,
		"KERNEL_STATUS_MEASUREMENT_ONLY": 3,
	}
)

func (x KernelStatus) Enum() *KernelStatus {
	p := new(KernelStatus)
	*p = x
	return p
}

func (x KernelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KernelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nydux_compiler_v1_kernel_proto_enumTypes[0].Descriptor()
}

func (KernelStatus) Type() protoreflect.EnumType {
	return &file_nydux_compiler_v1_kernel_proto_enumTypes[0]
}

func (x KernelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KernelStatus.Descriptor instead.
func (KernelStatus) EnumDescriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{0}
}

type WorkloadProfile int32

const (
	WorkloadProfile_WORKLOAD_PROFILE_UNSPECIFIED WorkloadProfile = 0
	WorkloadProfile_WORKLOAD_PROFILE_TRAINING    WorkloadProfile = 1
	WorkloadProfile_WORKLOAD_PROFILE_PREFILL     WorkloadProfile = 2
	WorkloadProfile_WORKLOAD_PROFILE_DECODE      WorkloadProfile = 3
	WorkloadProfile_WORKLOAD_PROFILE_HPC         WorkloadProfile = 4
)

// Enum value maps for WorkloadProfile.
var (
	WorkloadProfile_name = map[int32]string{
		0: "WORKLOAD_PROFILE_UNSPECIFIED",
		1: "WORKLOAD_PROFILE_TRAINING",
		2: "WORKLOAD_PROFILE_PREFILL",
		3: "WORKLOAD_PROFILE_DECODE",
		4: "WORKLOAD_PROFILE_HPC",
	}
	WorkloadProfile_value = map[string]int32{
		"WORKLOAD_PROFILE_UNSPECIFIED": 0,
		"WORKLOAD_PROFILE_TRAINING":    1,
		"WORKLOAD_PROFILE_PREFILL":     2,
		"WORKLOAD_PROFILE_DECODE":      3,
		"WORKLOAD_PROFILE_HPC":         4,
	}
)

func (x WorkloadProfile) Enum() *WorkloadProfile {
	p := new(WorkloadProfile)
	*p = x
	return p
}

func (x WorkloadProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_nydux_compiler_v1_kernel_proto_enumTypes[1].Descriptor()
}

func (WorkloadProfile) Type() protoreflect.EnumType {
	return &file_nydux_compiler_v1_kernel_proto_enumTypes[1]
}

func (x WorkloadProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadProfile.Descriptor instead.
func (WorkloadProfile) EnumDescriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{1}
}

type ToolchainRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Cuda          string                 `protobuf:"bytes,2,opt,name=cuda,proto3" json:"cuda,omitempty"`
	Ptxas         string                 `protobuf:"bytes,3,opt,name=ptxas,proto3" json:"ptxas,omitempty"`
	Triton        string                 `protobuf:"bytes,4,opt,name=triton,proto3" json:"triton,omitempty"`
	Torch         string                 `protobuf:"bytes,5,opt,name=torch,proto3" json:"torch,omitempty"`
	HostCc        string                 `protobuf:"bytes,6,opt,name=host_cc,json=hostCc,proto3" json:"host_cc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolchainRef) Reset() {
	*x = ToolchainRef{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolchainRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolchainRef) ProtoMessage() {}

func (x *ToolchainRef) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolchainRef.ProtoReflect.Descriptor instead.
func (*ToolchainRef) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *ToolchainRef) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *ToolchainRef) GetCuda() string {
	if x != nil {
		return x.Cuda
	}
	return ""
}

func (x *ToolchainRef) GetPtxas() string {
	if x != nil {
		return x.Ptxas
	}
	return ""
}

func (x *ToolchainRef) GetTriton() string {
	if x != nil {
		return x.Triton
	}
	return ""
}

func (x *ToolchainRef) GetTorch() string {
	if x != nil {
		return x.Torch
	}
	return ""
}

func (x *ToolchainRef) GetHostCc() string {
	if x != nil {
		return x.HostCc
	}
	return ""
}

type KernelScore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kes   float64                `protobuf:"fixed64,1,opt,name=kes,proto3" json:"kes,omitempty"`
	// Closed component set: roof, occ, stall, mem, tc, mix (ECD-003 §3.3).
	Components      map[string]float64 `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	KesModelVersion string             `protobuf:"bytes,3,opt,name=kes_model_version,json=kesModelVersion,proto3" json:"kes_model_version,omitempty"`
	Confidence      float64            `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ScoredAtNs      int64              `protobuf:"varint,5,opt,name=scored_at_ns,json=scoredAtNs,proto3" json:"scored_at_ns,omitempty"`
	Profile         WorkloadProfile    `protobuf:"varint,6,opt,name=profile,proto3,enum=nydux.compiler.v1.WorkloadProfile" json:"profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KernelScore) Reset() {
	*x = KernelScore{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelScore) ProtoMessage() {}

func (x *KernelScore) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelScore.ProtoReflect.Descriptor instead.
func (*KernelScore) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *KernelScore) GetKes() float64 {
	if x != nil {
		return x.Kes
	}
	return 0
}

func (x *KernelScore) GetComponents() map[string]float64 {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *KernelScore) GetKesModelVersion() string {
	if x != nil {
		return x.KesModelVersion
	}
	return ""
}

func (x *KernelScore) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *KernelScore) GetScoredAtNs() int64 {
	if x != nil {
		return x.ScoredAtNs
	}
	return 0
}

func (x *KernelScore) GetProfile() WorkloadProfile {
	if x != nil {
		return x.Profile
	}
	return WorkloadProfile_WORKLOAD_PROFILE_UNSPECIFIED
}

type Kernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelHash    string                 `protobuf:"bytes,1,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	FamilyHash    string                 `protobuf:"bytes,2,opt,name=family_hash,json=familyHash,proto3" json:"family_hash,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"` // e.g. "sm_90"
	Status        KernelStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=nydux.compiler.v1.KernelStatus" json:"status,omitempty"`
	Score         *KernelScore           `protobuf:"bytes,5,opt,name=score,proto3" json:"score,omitempty"` // unset when MEASUREMENT_ONLY
	Toolchain     *ToolchainRef          `protobuf:"bytes,6,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	PatternTags   []string               `protobuf:"bytes,7,rep,name=pattern_tags,json=patternTags,proto3" json:"pattern_tags,omitempty"`
	FirstSeenNs   int64                  `protobuf:"varint,8,opt,name=first_seen_ns,json=firstSeenNs,proto3" json:"first_seen_ns,omitempty"`
	LastSeenNs    int64                  `protobuf:"varint,9,opt,name=last_seen_ns,json=lastSeenNs,proto3" json:"last_seen_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kernel) Reset() {
	*x = Kernel{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kernel) ProtoMessage() {}

func (x *Kernel) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kernel.ProtoReflect.Descriptor instead.
func (*Kernel) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{2}
}

func (x *Kernel) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

func (x *Kernel) GetFamilyHash() string {
	if x != nil {
		return x.FamilyHash
	}
	return ""
}

func (x *Kernel) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Kernel) GetStatus() KernelStatus {
	if x != nil {
		return x.Status
	}
	return KernelStatus_KERNEL_STATUS_UNSPECIFIED
}

func (x *Kernel) GetScore() *KernelScore {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *Kernel) GetToolchain() *ToolchainRef {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *Kernel) GetPatternTags() []string {
	if x != nil {
		return x.PatternTags
	}
	return nil
}

func (x *Kernel) GetFirstSeenNs() int64 {
	if x != nil {
		return x.FirstSeenNs
	}
	return 0
}

func (x *Kernel) GetLastSeenNs() int64 {
	if x != nil {
		return x.LastSeenNs
	}
	return 0
}

type KernelGenerated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyHash    string                 `protobuf:"bytes,1,opt,name=family_hash,json=familyHash,proto3" json:"family_hash,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	IrFeatures    map[string]float64     `protobuf:"bytes,3,rep,name=ir_features,json=irFeatures,proto3" json:"ir_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // numeric allowlist only (RFC-003 D.9)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelGenerated) Reset() {
	*x = KernelGenerated{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelGenerated) ProtoMessage() {}

func (x *KernelGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelGenerated.ProtoReflect.Descriptor instead.
func (*KernelGenerated) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{3}
}

func (x *KernelGenerated) GetFamilyHash() string {
	if x != nil {
		return x.FamilyHash
	}
	return ""
}

func (x *KernelGenerated) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *KernelGenerated) GetIrFeatures() map[string]float64 {
	if x != nil {
		return x.IrFeatures
	}
	return nil
}

type KernelCompiled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelHash    string                 `protobuf:"bytes,1,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	Toolchain     *ToolchainRef          `protobuf:"bytes,2,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	Flags         []string               `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelCompiled) Reset() {
	*x = KernelCompiled{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelCompiled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelCompiled) ProtoMessage() {}

func (x *KernelCompiled) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelCompiled.ProtoReflect.Descriptor instead.
func (*KernelCompiled) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{4}
}

func (x *KernelCompiled) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

func (x *KernelCompiled) GetToolchain() *ToolchainRef {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *KernelCompiled) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type PtxGenerated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelHash    string                 `protobuf:"bytes,1,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	Regs          uint32                 `protobuf:"varint,2,opt,name=regs,proto3" json:"regs,omitempty"`
	InstrMix      map[string]uint32      `protobuf:"bytes,3,rep,name=instr_mix,json=instrMix,proto3" json:"instr_mix,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtxGenerated) Reset() {
	*x = PtxGenerated{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtxGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtxGenerated) ProtoMessage() {}

func (x *PtxGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtxGenerated.ProtoReflect.Descriptor instead.
func (*PtxGenerated) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{5}
}

func (x *PtxGenerated) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

func (x *PtxGenerated) GetRegs() uint32 {
	if x != nil {
		return x.Regs
	}
	return 0
}

func (x *PtxGenerated) GetInstrMix() map[string]uint32 {
	if x != nil {
		return x.InstrMix
	}
	return nil
}

type SassGenerated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KernelHash       string                 `protobuf:"bytes,1,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	Spills           uint32                 `protobuf:"varint,2,opt,name=spills,proto3" json:"spills,omitempty"`
	DecodeConfidence float64                `protobuf:"fixed64,3,opt,name=decode_confidence,json=decodeConfidence,proto3" json:"decode_confidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SassGenerated) Reset() {
	*x = SassGenerated{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SassGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SassGenerated) ProtoMessage() {}

func (x *SassGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SassGenerated.ProtoReflect.Descriptor instead.
func (*SassGenerated) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{6}
}

func (x *SassGenerated) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

func (x *SassGenerated) GetSpills() uint32 {
	if x != nil {
		return x.Spills
	}
	return 0
}

func (x *SassGenerated) GetDecodeConfidence() float64 {
	if x != nil {
		return x.DecodeConfidence
	}
	return 0
}

type KernelScored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelHash    string                 `protobuf:"bytes,1,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	FamilyHash    string                 `protobuf:"bytes,2,opt,name=family_hash,json=familyHash,proto3" json:"family_hash,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Score         *KernelScore           `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	Status        KernelStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=nydux.compiler.v1.KernelStatus" json:"status,omitempty"`
	ToolchainFp   string                 `protobuf:"bytes,6,opt,name=toolchain_fp,json=toolchainFp,proto3" json:"toolchain_fp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelScored) Reset() {
	*x = KernelScored{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelScored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelScored) ProtoMessage() {}

func (x *KernelScored) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelScored.ProtoReflect.Descriptor instead.
func (*KernelScored) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{7}
}

func (x *KernelScored) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

func (x *KernelScored) GetFamilyHash() string {
	if x != nil {
		return x.FamilyHash
	}
	return ""
}

func (x *KernelScored) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *KernelScored) GetScore() *KernelScore {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *KernelScored) GetStatus() KernelStatus {
	if x != nil {
		return x.Status
	}
	return KernelStatus_KERNEL_STATUS_UNSPECIFIED
}

func (x *KernelScored) GetToolchainFp() string {
	if x != nil {
		return x.ToolchainFp
	}
	return ""
}

type RegressionDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyHash    string                 `protobuf:"bytes,1,opt,name=family_hash,json=familyHash,proto3" json:"family_hash,omitempty"`
	From          *ToolchainRef          `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *ToolchainRef          `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	DeltaPerf     float64                `protobuf:"fixed64,4,opt,name=delta_perf,json=deltaPerf,proto3" json:"delta_perf,omitempty"` // fractional slowdown, >0 means regression
	CriContrib    float64                `protobuf:"fixed64,5,opt,name=cri_contrib,json=criContrib,proto3" json:"cri_contrib,omitempty"`
	MechanismTags []string               `protobuf:"bytes,6,rep,name=mechanism_tags,json=mechanismTags,proto3" json:"mechanism_tags,omitempty"` // e.g. "loop_unroll","sched","host_cc"
	ShapeClass    string                 `protobuf:"bytes,7,opt,name=shape_class,json=shapeClass,proto3" json:"shape_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegressionDetected) Reset() {
	*x = RegressionDetected{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegressionDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionDetected) ProtoMessage() {}

func (x *RegressionDetected) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionDetected.ProtoReflect.Descriptor instead.
func (*RegressionDetected) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{8}
}

func (x *RegressionDetected) GetFamilyHash() string {
	if x != nil {
		return x.FamilyHash
	}
	return ""
}

func (x *RegressionDetected) GetFrom() *ToolchainRef {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *RegressionDetected) GetTo() *ToolchainRef {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *RegressionDetected) GetDeltaPerf() float64 {
	if x != nil {
		return x.DeltaPerf
	}
	return 0
}

func (x *RegressionDetected) GetCriContrib() float64 {
	if x != nil {
		return x.CriContrib
	}
	return 0
}

func (x *RegressionDetected) GetMechanismTags() []string {
	if x != nil {
		return x.MechanismTags
	}
	return nil
}

func (x *RegressionDetected) GetShapeClass() string {
	if x != nil {
		return x.ShapeClass
	}
	return ""
}

type GetKernelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelHash    string                 `protobuf:"bytes,1,opt,name=kernel_hash,json=kernelHash,proto3" json:"kernel_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKernelRequest) Reset() {
	*x = GetKernelRequest{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKernelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKernelRequest) ProtoMessage() {}

func (x *GetKernelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKernelRequest.ProtoReflect.Descriptor instead.
func (*GetKernelRequest) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{9}
}

func (x *GetKernelRequest) GetKernelHash() string {
	if x != nil {
		return x.KernelHash
	}
	return ""
}

type ListKernelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RSQL subset over whitelisted fields: kes, arch, status, family_hash (ECD-003 §3.8).
	Filter        string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort          string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"` // e.g. "-kes"
	Limit         int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque keyset cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKernelsRequest) Reset() {
	*x = ListKernelsRequest{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKernelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKernelsRequest) ProtoMessage() {}

func (x *ListKernelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKernelsRequest.ProtoReflect.Descriptor instead.
func (*ListKernelsRequest) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{10}
}

func (x *ListKernelsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListKernelsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListKernelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListKernelsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListKernelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Kernel              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKernelsResponse) Reset() {
	*x = ListKernelsResponse{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKernelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKernelsResponse) ProtoMessage() {}

func (x *ListKernelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKernelsResponse.ProtoReflect.Descriptor instead.
func (*ListKernelsResponse) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{11}
}

func (x *ListKernelsResponse) GetItems() []*Kernel {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListKernelsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type CheckRegressionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  *ToolchainRef          `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To    *ToolchainRef          `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Gate expression grammar (ECD-002 ASM-002-1): "CRI>0.10" | "CRI>=0.10".
	FailOn        string `protobuf:"bytes,3,opt,name=fail_on,json=failOn,proto3" json:"fail_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegressionsRequest) Reset() {
	*x = CheckRegressionsRequest{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegressionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegressionsRequest) ProtoMessage() {}

func (x *CheckRegressionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegressionsRequest.ProtoReflect.Descriptor instead.
func (*CheckRegressionsRequest) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{12}
}

func (x *CheckRegressionsRequest) GetFrom() *ToolchainRef {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CheckRegressionsRequest) GetTo() *ToolchainRef {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CheckRegressionsRequest) GetFailOn() string {
	if x != nil {
		return x.FailOn
	}
	return ""
}

type CheckRegressionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetCri      float64                `protobuf:"fixed64,1,opt,name=fleet_cri,json=fleetCri,proto3" json:"fleet_cri,omitempty"`
	GatePassed    bool                   `protobuf:"varint,2,opt,name=gate_passed,json=gatePassed,proto3" json:"gate_passed,omitempty"`
	Regressions   []*RegressionDetected  `protobuf:"bytes,3,rep,name=regressions,proto3" json:"regressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegressionsResponse) Reset() {
	*x = CheckRegressionsResponse{}
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegressionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegressionsResponse) ProtoMessage() {}

func (x *CheckRegressionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_compiler_v1_kernel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegressionsResponse.ProtoReflect.Descriptor instead.
func (*CheckRegressionsResponse) Descriptor() ([]byte, []int) {
	return file_nydux_compiler_v1_kernel_proto_rawDescGZIP(), []int{13}
}

func (x *CheckRegressionsResponse) GetFleetCri() float64 {
	if x != nil {
		return x.FleetCri
	}
	return 0
}

func (x *CheckRegressionsResponse) GetGatePassed() bool {
	if x != nil {
		return x.GatePassed
	}
	return false
}

func (x *CheckRegressionsResponse) GetRegressions() []*RegressionDetected {
	if x != nil {
		return x.Regressions
	}
	return nil
}

var File_nydux_compiler_v1_kernel_proto protoreflect.FileDescriptor

const file_nydux_compiler_v1_kernel_proto_rawDesc = "" +
	"\n" +
	"\x1enydux/compiler/v1/kernel.proto\x12\x11nydux.compiler.v1\x1a\x1bbuf/validate/validate.proto\"\xbb\x01\n" +
	"\fToolchainRef\x12:\n" +
	"\vfingerprint\x18\x01 \x01(\tB\x18\xbaH\x15r\x132\x0e^[a-f0-9]{64}$\x98\x01@R\vfingerprint\x12\x12\n" +
	"\x04cuda\x18\x02 \x01(\tR\x04cuda\x12\x14\n" +
	"\x05ptxas\x18\x03 \x01(\tR\x05ptxas\x12\x16\n" +
	"\x06triton\x18\x04 \x01(\tR\x06triton\x12\x14\n" +
	"\x05torch\x18\x05 \x01(\tR\x05torch\x12\x17\n" +
	"\ahost_cc\x18\x06 \x01(\tR\x06hostCc\"\x95\x03\n" +
	"\vKernelScore\x12)\n" +
	"\x03kes\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00R\x03kes\x12N\n" +
	"\n" +
	"components\x18\x02 \x03(\v2..nydux.compiler.v1.KernelScore.ComponentsEntryR\n" +
	"components\x123\n" +
	"\x11kes_model_version\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fkesModelVersion\x127\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"confidence\x12 \n" +
	"\fscored_at_ns\x18\x05 \x01(\x03R\n" +
	"scoredAtNs\x12<\n" +
	"\aprofile\x18\x06 \x01(\x0e2\".nydux.compiler.v1.WorkloadProfileR\aprofile\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb4\x03\n" +
	"\x06Kernel\x129\n" +
	"\vkernel_hash\x18\x01 \x01(\tB\x18\xbaH\x15r\x132\x0e^[a-f0-9]{64}$\x98\x01@R\n" +
	"kernelHash\x129\n" +
	"\vfamily_hash\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x0e^[a-f0-9]{64}$\x98\x01@R\n" +
	"familyHash\x12\x1d\n" +
	"\x04arch\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x04\x18\x10R\x04arch\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.nydux.compiler.v1.KernelStatusR\x06status\x124\n" +
	"\x05score\x18\x05 \x01(\v2\x1e.nydux.compiler.v1.KernelScoreR\x05score\x12=\n" +
	"\ttoolchain\x18\x06 \x01(\v2\x1f.nydux.compiler.v1.ToolchainRefR\ttoolchain\x12!\n" +
	"\fpattern_tags\x18\a \x03(\tR\vpatternTags\x12\"\n" +
	"\rfirst_seen_ns\x18\b \x01(\x03R\vfirstSeenNs\x12 \n" +
	"\flast_seen_ns\x18\t \x01(\x03R\n" +
	"lastSeenNs\"\x8a\x02\n" +
	"\x0fKernelGenerated\x12\x1f\n" +
	"\vfamily_hash\x18\x01 \x01(\tR\n" +
	"familyHash\x12B\n" +
	"\x06source\x18\x02 \x01(\tB*\xbaH'r%R\x06tritonR\binductorR\x03xlaR\x04cudaR\x06cublasR\x06source\x12S\n" +
	"\vir_features\x18\x03 \x03(\v22.nydux.compiler.v1.KernelGenerated.IrFeaturesEntryR\n" +
	"irFeatures\x1a=\n" +
	"\x0fIrFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x86\x01\n" +
	"\x0eKernelCompiled\x12\x1f\n" +
	"\vkernel_hash\x18\x01 \x01(\tR\n" +
	"kernelHash\x12=\n" +
	"\ttoolchain\x18\x02 \x01(\v2\x1f.nydux.compiler.v1.ToolchainRefR\ttoolchain\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\"\xcc\x01\n" +
	"\fPtxGenerated\x12\x1f\n" +
	"\vkernel_hash\x18\x01 \x01(\tR\n" +
	"kernelHash\x12\x12\n" +
	"\x04regs\x18\x02 \x01(\rR\x04regs\x12J\n" +
	"\tinstr_mix\x18\x03 \x03(\v2-.nydux.compiler.v1.PtxGenerated.InstrMixEntryR\binstrMix\x1a;\n" +
	"\rInstrMixEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x8e\x01\n" +
	"\rSassGenerated\x12\x1f\n" +
	"\vkernel_hash\x18\x01 \x01(\tR\n" +
	"kernelHash\x12\x16\n" +
	"\x06spills\x18\x02 \x01(\rR\x06spills\x12D\n" +
	"\x11decode_confidence\x18\x03 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\x10decodeConfidence\"\xf6\x01\n" +
	"\fKernelScored\x12\x1f\n" +
	"\vkernel_hash\x18\x01 \x01(\tR\n" +
	"kernelHash\x12\x1f\n" +
	"\vfamily_hash\x18\x02 \x01(\tR\n" +
	"familyHash\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x124\n" +
	"\x05score\x18\x04 \x01(\v2\x1e.nydux.compiler.v1.KernelScoreR\x05score\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.nydux.compiler.v1.KernelStatusR\x06status\x12!\n" +
	"\ftoolchain_fp\x18\x06 \x01(\tR\vtoolchainFp\"\xb3\x02\n" +
	"\x12RegressionDetected\x12\x1f\n" +
	"\vfamily_hash\x18\x01 \x01(\tR\n" +
	"familyHash\x123\n" +
	"\x04from\x18\x02 \x01(\v2\x1f.nydux.compiler.v1.ToolchainRefR\x04from\x12/\n" +
	"\x02to\x18\x03 \x01(\v2\x1f.nydux.compiler.v1.ToolchainRefR\x02to\x12\x1d\n" +
	"\n" +
	"delta_perf\x18\x04 \x01(\x01R\tdeltaPerf\x12/\n" +
	"\vcri_contrib\x18\x05 \x01(\x01B\x0e\xbaH\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"criContrib\x12%\n" +
	"\x0emechanism_tags\x18\x06 \x03(\tR\rmechanismTags\x12\x1f\n" +
	"\vshape_class\x18\a \x01(\tR\n" +
	"shapeClass\"=\n" +
	"\x10GetKernelRequest\x12)\n" +
	"\vkernel_hash\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\n" +
	"kernelHash\"\x84\x01\n" +
	"\x12ListKernelsRequest\x12 \n" +
	"\x06filter\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x04R\x06filter\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12 \n" +
	"\x05limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03(\x01R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"g\n" +
	"\x13ListKernelsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.nydux.compiler.v1.KernelR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xb8\x01\n" +
	"\x17CheckRegressionsRequest\x123\n" +
	"\x04from\x18\x01 \x01(\v2\x1f.nydux.compiler.v1.ToolchainRefR\x04from\x12/\n" +
	"\x02to\x18\x02 \x01(\v2\x1f.nydux.compiler.v1.ToolchainRefR\x02to\x127\n" +
	"\afail_on\x18\x03 \x01(\tB\x1e\xbaH\x1br\x192\x17^CRI>=?[0-9]*\\.?[0-9]+$R\x06failOn\"\xa1\x01\n" +
	"\x18CheckRegressionsResponse\x12\x1b\n" +
	"\tfleet_cri\x18\x01 \x01(\x01R\bfleetCri\x12\x1f\n" +
	"\vgate_passed\x18\x02 \x01(\bR\n" +
	"gatePassed\x12G\n" +
	"\vregressions\x18\x03 \x03(\v2%.nydux.compiler.v1.RegressionDetectedR\vregressions*\x8e\x01\n" +
	"\fKernelStatus\x12\x1d\n" +
	"\x19KERNEL_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14KERNEL_STATUS_SCORED\x10\x01\x12!\n" +
	"\x1dKERNEL_STATUS_STATIC_ESTIMATE\x10\x02\x12\"\n" +
	"\x1eKERNEL_STATUS_MEASUREMENT_ONLY\x10\x03*\xa7\x01\n" +
	"\x0fWorkloadProfile\x12 \n" +
	"\x1cWORKLOAD_PROFILE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKLOAD_PROFILE_TRAINING\x10\x01\x12\x1c\n" +
	"\x18WORKLOAD_PROFILE_PREFILL\x10\x02\x12\x1b\n" +
	"\x17WORKLOAD_PROFILE_DECODE\x10\x03\x12\x18\n" +
	"\x14WORKLOAD_PROFILE_HPC\x10\x042\x94\x02\n" +
	"\rKernelService\x12K\n" +
	"\tGetKernel\x12#.nydux.compiler.v1.GetKernelRequest\x1a\x19.nydux.compiler.v1.Kernel\x12\\\n" +
	"\vListKernels\x12%.nydux.compiler.v1.ListKernelsRequest\x1a&.nydux.compiler.v1.ListKernelsResponse\x12X\n" +
	"\fStreamScores\x12%.nydux.compiler.v1.ListKernelsRequest\x1a\x1f.nydux.compiler.v1.KernelScored0\x012\x80\x01\n" +
	"\x11RegressionService\x12k\n" +
	"\x10CheckRegressions\x12*.nydux.compiler.v1.CheckRegressionsRequest\x1a+.nydux.compiler.v1.CheckRegressionsResponseB<Z:github.com/nydux/platform/api/nydux/compiler/v1;compilerv1b\x06proto3"

var (
	file_nydux_compiler_v1_kernel_proto_rawDescOnce sync.Once
	file_nydux_compiler_v1_kernel_proto_rawDescData []byte
)

func file_nydux_compiler_v1_kernel_proto_rawDescGZIP() []byte {
	file_nydux_compiler_v1_kernel_proto_rawDescOnce.Do(func() {
		file_nydux_compiler_v1_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_compiler_v1_kernel_proto_rawDesc), len(file_nydux_compiler_v1_kernel_proto_rawDesc)))
	})
	return file_nydux_compiler_v1_kernel_proto_rawDescData
}

var file_nydux_compiler_v1_kernel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nydux_compiler_v1_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_nydux_compiler_v1_kernel_proto_goTypes = []any{
	(KernelStatus)(0),                // 0: nydux.compiler.v1.KernelStatus
	(WorkloadProfile)(0),             // 1: nydux.compiler.v1.WorkloadProfile
	(*ToolchainRef)(nil),             // 2: nydux.compiler.v1.ToolchainRef
	(*KernelScore)(nil),              // 3: nydux.compiler.v1.KernelScore
	(*Kernel)(nil),                   // 4: nydux.compiler.v1.Kernel
	(*KernelGenerated)(nil),          // 5: nydux.compiler.v1.KernelGenerated
	(*KernelCompiled)(nil),           // 6: nydux.compiler.v1.KernelCompiled
	(*PtxGenerated)(nil),             // 7: nydux.compiler.v1.PtxGenerated
	(*SassGenerated)(nil),            // 8: nydux.compiler.v1.SassGenerated
	(*KernelScored)(nil),             // 9: nydux.compiler.v1.KernelScored
	(*RegressionDetected)(nil),       // 10: nydux.compiler.v1.RegressionDetected
	(*GetKernelRequest)(nil),         // 11: nydux.compiler.v1.GetKernelRequest
	(*ListKernelsRequest)(nil),       // 12: nydux.compiler.v1.ListKernelsRequest
	(*ListKernelsResponse)(nil),      // 13: nydux.compiler.v1.ListKernelsResponse
	(*CheckRegressionsRequest)(nil),  // 14: nydux.compiler.v1.CheckRegressionsRequest
	(*CheckRegressionsResponse)(nil), // 15: nydux.compiler.v1.CheckRegressionsResponse
	nil,                              // 16: nydux.compiler.v1.KernelScore.ComponentsEntry
	nil,                              // 17: nydux.compiler.v1.KernelGenerated.IrFeaturesEntry
	nil,                              // 18: nydux.compiler.v1.PtxGenerated.InstrMixEntry
}
var file_nydux_compiler_v1_kernel_proto_depIdxs = []int32{
	16, // 0: nydux.compiler.v1.KernelScore.components:type_name -> nydux.compiler.v1.KernelScore.ComponentsEntry
	1,  // 1: nydux.compiler.v1.KernelScore.profile:type_name -> nydux.compiler.v1.WorkloadProfile
	0,  // 2: nydux.compiler.v1.Kernel.status:type_name -> nydux.compiler.v1.KernelStatus
	3,  // 3: nydux.compiler.v1.Kernel.score:type_name -> nydux.compiler.v1.KernelScore
	2,  // 4: nydux.compiler.v1.Kernel.toolchain:type_name -> nydux.compiler.v1.ToolchainRef
	17, // 5: nydux.compiler.v1.KernelGenerated.ir_features:type_name -> nydux.compiler.v1.KernelGenerated.IrFeaturesEntry
	2,  // 6: nydux.compiler.v1.KernelCompiled.toolchain:type_name -> nydux.compiler.v1.ToolchainRef
	18, // 7: nydux.compiler.v1.PtxGenerated.instr_mix:type_name -> nydux.compiler.v1.PtxGenerated.InstrMixEntry
	3,  // 8: nydux.compiler.v1.KernelScored.score:type_name -> nydux.compiler.v1.KernelScore
	0,  // 9: nydux.compiler.v1.KernelScored.status:type_name -> nydux.compiler.v1.KernelStatus
	2,  // 10: nydux.compiler.v1.RegressionDetected.from:type_name -> nydux.compiler.v1.ToolchainRef
	2,  // 11: nydux.compiler.v1.RegressionDetected.to:type_name -> nydux.compiler.v1.ToolchainRef
	4,  // 12: nydux.compiler.v1.ListKernelsResponse.items:type_name -> nydux.compiler.v1.Kernel
	2,  // 13: nydux.compiler.v1.CheckRegressionsRequest.from:type_name -> nydux.compiler.v1.ToolchainRef
	2,  // 14: nydux.compiler.v1.CheckRegressionsRequest.to:type_name -> nydux.compiler.v1.ToolchainRef
	10, // 15: nydux.compiler.v1.CheckRegressionsResponse.regressions:type_name -> nydux.compiler.v1.RegressionDetected
	11, // 16: nydux.compiler.v1.KernelService.GetKernel:input_type -> nydux.compiler.v1.GetKernelRequest
	12, // 17: nydux.compiler.v1.KernelService.ListKernels:input_type -> nydux.compiler.v1.ListKernelsRequest
	12, // 18: nydux.compiler.v1.KernelService.StreamScores:input_type -> nydux.compiler.v1.ListKernelsRequest
	14, // 19: nydux.compiler.v1.RegressionService.CheckRegressions:input_type -> nydux.compiler.v1.CheckRegressionsRequest
	4,  // 20: nydux.compiler.v1.KernelService.GetKernel:output_type -> nydux.compiler.v1.Kernel
	13, // 21: nydux.compiler.v1.KernelService.ListKernels:output_type -> nydux.compiler.v1.ListKernelsResponse
	9,  // 22: nydux.compiler.v1.KernelService.StreamScores:output_type -> nydux.compiler.v1.KernelScored
	15, // 23: nydux.compiler.v1.RegressionService.CheckRegressions:output_type -> nydux.compiler.v1.CheckRegressionsResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_nydux_compiler_v1_kernel_proto_init() }
func file_nydux_compiler_v1_kernel_proto_init() {
	if File_nydux_compiler_v1_kernel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_compiler_v1_kernel_proto_rawDesc), len(file_nydux_compiler_v1_kernel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_nydux_compiler_v1_kernel_proto_goTypes,
		DependencyIndexes: file_nydux_compiler_v1_kernel_proto_depIdxs,
		EnumInfos:         file_nydux_compiler_v1_kernel_proto_enumTypes,
		MessageInfos:      file_nydux_compiler_v1_kernel_proto_msgTypes,
	}.Build()
	File_nydux_compiler_v1_kernel_proto = out.File
	file_nydux_compiler_v1_kernel_proto_goTypes = nil
	file_nydux_compiler_v1_kernel_proto_depIdxs = nil
}
