// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/agent/v1/agent.proto

package agentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TokensIn        uint64                 `protobuf:"varint,4,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut       uint64                 `protobuf:"varint,5,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	BudgetUsdMicros int64                  `protobuf:"varint,6,opt,name=budget_usd_micros,json=budgetUsdMicros,proto3" json:"budget_usd_micros,omitempty"`
	TranscriptUri   string                 `protobuf:"bytes,7,opt,name=transcript_uri,json=transcriptUri,proto3" json:"transcript_uri,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_nydux_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_nydux_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Task) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Task) GetTokensIn() uint64 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *Task) GetTokensOut() uint64 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

func (x *Task) GetBudgetUsdMicros() int64 {
	if x != nil {
		return x.BudgetUsdMicros
	}
	return 0
}

func (x *Task) GetTranscriptUri() string {
	if x != nil {
		return x.TranscriptUri
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	ArgsJson      []byte                 `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	ArgsHash      []byte                 `protobuf:"bytes,4,opt,name=args_hash,json=argsHash,proto3" json:"args_hash,omitempty"` // BLAKE3, audited
	WriteClass    bool                   `protobuf:"varint,5,opt,name=write_class,json=writeClass,proto3" json:"write_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_nydux_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_nydux_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ToolCall) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCall) GetArgsJson() []byte {
	if x != nil {
		return x.ArgsJson
	}
	return nil
}

func (x *ToolCall) GetArgsHash() []byte {
	if x != nil {
		return x.ArgsHash
	}
	return nil
}

func (x *ToolCall) GetWriteClass() bool {
	if x != nil {
		return x.WriteClass
	}
	return false
}

type TaskCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleted) Reset() {
	*x = TaskCompleted{}
	mi := &file_nydux_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleted) ProtoMessage() {}

func (x *TaskCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleted.ProtoReflect.Descriptor instead.
func (*TaskCompleted) Descriptor() ([]byte, []int) {
	return file_nydux_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCompleted) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskCompleted) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_nydux_agent_v1_agent_proto protoreflect.FileDescriptor

const file_nydux_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1anydux/agent/v1/agent.proto\x12\x0enydux.agent.v1\x1a\x1bbuf/validate/validate.proto\"\xa1\x03\n" +
	"\x04Task\x12!\n" +
	"\atask_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06taskId\x12\x8a\x01\n" +
	"\x04kind\x18\x02 \x01(\tBv\xbaHsrqR\fcompiler_optR\x0fkernel_analysisR\bcost_optR\bcapacityR\n" +
	"governanceR\ffailure_predR\x03rcaR\n" +
	"twin_calibR\aadvisorR\bdecisionR\x04kind\x12Z\n" +
	"\x05state\x18\x03 \x01(\tBD\xbaHAr?R\acreatedR\bplanningR\texecutingR\x11awaiting_approvalR\x04doneR\x06failedR\x05state\x12\x1b\n" +
	"\ttokens_in\x18\x04 \x01(\x04R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\x05 \x01(\x04R\ttokensOut\x12*\n" +
	"\x11budget_usd_micros\x18\x06 \x01(\x03R\x0fbudgetUsdMicros\x12%\n" +
	"\x0etranscript_uri\x18\a \x01(\tR\rtranscriptUri\"\x9b\x01\n" +
	"\bToolCall\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\fR\bargsJson\x12$\n" +
	"\targs_hash\x18\x04 \x01(\fB\a\xbaH\x04z\x02h R\bargsHash\x12\x1f\n" +
	"\vwrite_class\x18\x05 \x01(\bR\n" +
	"writeClass\"\x91\x01\n" +
	"\rTaskCompleted\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.nydux.agent.v1.TaskR\x04task\x12V\n" +
	"\aoutcome\x18\x02 \x01(\tB<\xbaH9r7R\asuccessR\fjudge_rejectR\x0fbudget_exceededR\x06killedR\x05errorR\aoutcomeB6Z4github.com/nydux/platform/api/nydux/agent/v1;agentv1b\x06proto3"

var (
	file_nydux_agent_v1_agent_proto_rawDescOnce sync.Once
	file_nydux_agent_v1_agent_proto_rawDescData []byte
)

func file_nydux_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_nydux_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_nydux_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_agent_v1_agent_proto_rawDesc), len(file_nydux_agent_v1_agent_proto_rawDesc)))
	})
	return file_nydux_agent_v1_agent_proto_rawDescData
}

var file_nydux_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nydux_agent_v1_agent_proto_goTypes = []any{
	(*Task)(nil),          // 0: nydux.agent.v1.Task
	(*ToolCall)(nil),      // 1: nydux.agent.v1.ToolCall
	(*TaskCompleted)(nil), // 2: nydux.agent.v1.TaskCompleted
}
var file_nydux_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: nydux.agent.v1.TaskCompleted.task:type_name -> nydux.agent.v1.Task
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nydux_agent_v1_agent_proto_init() }
func file_nydux_agent_v1_agent_proto_init() {
	if File_nydux_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_agent_v1_agent_proto_rawDesc), len(file_nydux_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nydux_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_nydux_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_nydux_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_nydux_agent_v1_agent_proto = out.File
	file_nydux_agent_v1_agent_proto_goTypes = nil
	file_nydux_agent_v1_agent_proto_depIdxs = nil
}
