// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nydux/graph/v1/graph.proto

package graphv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphQueryService_NamedQuery_FullMethodName = "/nydux.graph.v1.GraphQueryService/NamedQuery"
)

// GraphQueryServiceClient is the client API for GraphQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphQueryServiceClient interface {
	NamedQuery(ctx context.Context, in *NamedQueryRequest, opts ...grpc.CallOption) (*NamedQueryResponse, error)
}

type graphQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphQueryServiceClient(cc grpc.ClientConnInterface) GraphQueryServiceClient {
	return &graphQueryServiceClient{cc}
}

func (c *graphQueryServiceClient) NamedQuery(ctx context.Context, in *NamedQueryRequest, opts ...grpc.CallOption) (*NamedQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamedQueryResponse)
	err := c.cc.Invoke(ctx, GraphQueryService_NamedQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphQueryServiceServer is the server API for GraphQueryService service.
// All implementations must embed UnimplementedGraphQueryServiceServer
// for forward compatibility.
type GraphQueryServiceServer interface {
	NamedQuery(context.Context, *NamedQueryRequest) (*NamedQueryResponse, error)
	mustEmbedUnimplementedGraphQueryServiceServer()
}

// UnimplementedGraphQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphQueryServiceServer struct{}

func (UnimplementedGraphQueryServiceServer) NamedQuery(context.Context, *NamedQueryRequest) (*NamedQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NamedQuery not implemented")
}
func (UnimplementedGraphQueryServiceServer) mustEmbedUnimplementedGraphQueryServiceServer() {}
func (UnimplementedGraphQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeGraphQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphQueryServiceServer will
// result in compilation errors.
type UnsafeGraphQueryServiceServer interface {
	mustEmbedUnimplementedGraphQueryServiceServer()
}

func RegisterGraphQueryServiceServer(s grpc.ServiceRegistrar, srv GraphQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedGraphQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphQueryService_ServiceDesc, srv)
}

func _GraphQueryService_NamedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamedQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphQueryServiceServer).NamedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphQueryService_NamedQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphQueryServiceServer).NamedQuery(ctx, req.(*NamedQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphQueryService_ServiceDesc is the grpc.ServiceDesc for GraphQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nydux.graph.v1.GraphQueryService",
	HandlerType: (*GraphQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NamedQuery",
			Handler:    _GraphQueryService_NamedQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nydux/graph/v1/graph.proto",
}
