// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nydux/graph/v1/graph.proto

package graphv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Props         map[string]string      `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // allowlisted per label (RFC-003 D.3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_nydux_graph_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Rel           string                 `protobuf:"bytes,3,opt,name=rel,proto3" json:"rel,omitempty"`
	Props         map[string]string      `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_nydux_graph_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Edge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Edge) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

func (x *Edge) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

type NamedQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedQueryRequest) Reset() {
	*x = NamedQueryRequest{}
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedQueryRequest) ProtoMessage() {}

func (x *NamedQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedQueryRequest.ProtoReflect.Descriptor instead.
func (*NamedQueryRequest) Descriptor() ([]byte, []int) {
	return file_nydux_graph_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *NamedQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *NamedQueryRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type NamedQueryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Nodes                []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	FreshnessWatermarkNs int64                  `protobuf:"varint,3,opt,name=freshness_watermark_ns,json=freshnessWatermarkNs,proto3" json:"freshness_watermark_ns,omitempty"`
	FromMaterializedView bool                   `protobuf:"varint,4,opt,name=from_materialized_view,json=fromMaterializedView,proto3" json:"from_materialized_view,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NamedQueryResponse) Reset() {
	*x = NamedQueryResponse{}
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedQueryResponse) ProtoMessage() {}

func (x *NamedQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nydux_graph_v1_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedQueryResponse.ProtoReflect.Descriptor instead.
func (*NamedQueryResponse) Descriptor() ([]byte, []int) {
	return file_nydux_graph_v1_graph_proto_rawDescGZIP(), []int{3}
}

func (x *NamedQueryResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NamedQueryResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *NamedQueryResponse) GetFreshnessWatermarkNs() int64 {
	if x != nil {
		return x.FreshnessWatermarkNs
	}
	return 0
}

func (x *NamedQueryResponse) GetFromMaterializedView() bool {
	if x != nil {
		return x.FromMaterializedView
	}
	return false
}

var File_nydux_graph_v1_graph_proto protoreflect.FileDescriptor

const file_nydux_graph_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x1anydux/graph/v1/graph.proto\x12\x0enydux.graph.v1\x1a\x1bbuf/validate/validate.proto\"\xbd\x02\n" +
	"\x04Node\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\xaa\x01\n" +
	"\x05label\x18\x02 \x01(\tB\x93\x01\xbaH\x8f\x01r\x8c\x01R\fKernelFamilyR\rKernelVariantR\tToolchainR\x05ModelR\bWorkloadR\aClusterR\x04NodeR\x03GpuR\n" +
	"DeploymentR\x04TeamR\tCostSliceR\x0eRecommendationR\bIncidentR\x06PolicyR\x05label\x125\n" +
	"\x05props\x18\x03 \x03(\v2\x1f.nydux.graph.v1.Node.PropsEntryR\x05props\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\x04Edge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x94\x01\n" +
	"\x03rel\x18\x03 \x01(\tB\x81\x01\xbaH~r|R\n" +
	"VARIANT_OFR\rCOMPILED_WITHR\aRUNS_ONR\aPART_OFR\bOWNED_BYR\x05COSTSR\fREGRESSED_BYR\x0fRECOMMENDED_FORR\vRESULTED_INR\bVIOLATESR\x06CAUSEDR\x03rel\x125\n" +
	"\x05props\x18\x04 \x03(\v2\x1f.nydux.graph.v1.Edge.PropsEntryR\x05props\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x11NamedQueryRequest\x12c\n" +
	"\x05query\x18\x01 \x01(\tBM\xbaHJrHR\treg_blastR\x0ecost_to_kernelR\ttop_wasteR\x0fsimilar_kernelsR\x0fincident_causesR\x05query\x12E\n" +
	"\x06params\x18\x02 \x03(\v2-.nydux.graph.v1.NamedQueryRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x12NamedQueryResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.nydux.graph.v1.NodeR\x05nodes\x12*\n" +
	"\x05edges\x18\x02 \x03(\v2\x14.nydux.graph.v1.EdgeR\x05edges\x124\n" +
	"\x16freshness_watermark_ns\x18\x03 \x01(\x03R\x14freshnessWatermarkNs\x124\n" +
	"\x16from_materialized_view\x18\x04 \x01(\bR\x14fromMaterializedView2h\n" +
	"\x11GraphQueryService\x12S\n" +
	"\n" +
	"NamedQuery\x12!.nydux.graph.v1.NamedQueryRequest\x1a\".nydux.graph.v1.NamedQueryResponseB6Z4github.com/nydux/platform/api/nydux/graph/v1;graphv1b\x06proto3"

var (
	file_nydux_graph_v1_graph_proto_rawDescOnce sync.Once
	file_nydux_graph_v1_graph_proto_rawDescData []byte
)

func file_nydux_graph_v1_graph_proto_rawDescGZIP() []byte {
	file_nydux_graph_v1_graph_proto_rawDescOnce.Do(func() {
		file_nydux_graph_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nydux_graph_v1_graph_proto_rawDesc), len(file_nydux_graph_v1_graph_proto_rawDesc)))
	})
	return file_nydux_graph_v1_graph_proto_rawDescData
}

var file_nydux_graph_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nydux_graph_v1_graph_proto_goTypes = []any{
	(*Node)(nil),               // 0: nydux.graph.v1.Node
	(*Edge)(nil),               // 1: nydux.graph.v1.Edge
	(*NamedQueryRequest)(nil),  // 2: nydux.graph.v1.NamedQueryRequest
	(*NamedQueryResponse)(nil), // 3: nydux.graph.v1.NamedQueryResponse
	nil,                        // 4: nydux.graph.v1.Node.PropsEntry
	nil,                        // 5: nydux.graph.v1.Edge.PropsEntry
	nil,                        // 6: nydux.graph.v1.NamedQueryRequest.ParamsEntry
}
var file_nydux_graph_v1_graph_proto_depIdxs = []int32{
	4, // 0: nydux.graph.v1.Node.props:type_name -> nydux.graph.v1.Node.PropsEntry
	5, // 1: nydux.graph.v1.Edge.props:type_name -> nydux.graph.v1.Edge.PropsEntry
	6, // 2: nydux.graph.v1.NamedQueryRequest.params:type_name -> nydux.graph.v1.NamedQueryRequest.ParamsEntry
	0, // 3: nydux.graph.v1.NamedQueryResponse.nodes:type_name -> nydux.graph.v1.Node
	1, // 4: nydux.graph.v1.NamedQueryResponse.edges:type_name -> nydux.graph.v1.Edge
	2, // 5: nydux.graph.v1.GraphQueryService.NamedQuery:input_type -> nydux.graph.v1.NamedQueryRequest
	3, // 6: nydux.graph.v1.GraphQueryService.NamedQuery:output_type -> nydux.graph.v1.NamedQueryResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_nydux_graph_v1_graph_proto_init() }
func file_nydux_graph_v1_graph_proto_init() {
	if File_nydux_graph_v1_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nydux_graph_v1_graph_proto_rawDesc), len(file_nydux_graph_v1_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nydux_graph_v1_graph_proto_goTypes,
		DependencyIndexes: file_nydux_graph_v1_graph_proto_depIdxs,
		MessageInfos:      file_nydux_graph_v1_graph_proto_msgTypes,
	}.Build()
	File_nydux_graph_v1_graph_proto = out.File
	file_nydux_graph_v1_graph_proto_goTypes = nil
	file_nydux_graph_v1_graph_proto_depIdxs = nil
}
